export type Route = {
  slug: string;
  fromCity: string;
  toCity: string;
  distance: number;
  duration: string;
};

export const ROUTES: Route[] = [
  // --- Existing Core Routes ---
  {
    slug: "noida-to-delhi",
    fromCity: "Noida",
    toCity: "Delhi",
    distance: 25,
    duration: "45 min - 1.5 hrs",
  },
  {
    slug: "lucknow-to-ayodhya",
    fromCity: "Lucknow",
    toCity: "Ayodhya",
    distance: 135,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "noida-to-agra",
    fromCity: "Noida",
    toCity: "Agra",
    distance: 200,
    duration: "4 - 5 hrs",
  },
  {
    slug: "noida-to-jaipur",
    fromCity: "Noida",
    toCity: "Jaipur",
    distance: 280,
    duration: "5 - 6 hrs",
  },
  {
    slug: "noida-to-haridwar",
    fromCity: "Noida",
    toCity: "Haridwar",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "noida-to-mathura",
    fromCity: "Noida",
    toCity: "Mathura",
    distance: 160,
    duration: "3 - 4 hrs",
  },
  {
    slug: "noida-to-vrindavan",
    fromCity: "Noida",
    toCity: "Vrindavan",
    distance: 165,
    duration: "3 - 4 hrs",
  },
  {
    slug: "lucknow-to-varanasi",
    fromCity: "Lucknow",
    toCity: "Varanasi",
    distance: 320,
    duration: "6 - 7 hrs",
  },

  // --- Varanasi Nearby Routes ---
  {
    slug: "varanasi-to-prayagraj",
    fromCity: "Varanasi",
    toCity: "Prayagraj",
    distance: 120,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "varanasi-to-sarnath",
    fromCity: "Varanasi",
    toCity: "Sarnath",
    distance: 10,
    duration: "20 - 30 min",
  },
  {
    slug: "varanasi-to-mirzapur",
    fromCity: "Varanasi",
    toCity: "Mirzapur",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "varanasi-to-ayodhya",
    fromCity: "Varanasi",
    toCity: "Ayodhya",
    distance: 200,
    duration: "4 - 5 hrs",
  },
  {
    slug: "varanasi-to-gaya",
    fromCity: "Varanasi",
    toCity: "Gaya",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "varanasi-to-vindhyachal",
    fromCity: "Varanasi",
    toCity: "Vindhyachal",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "varanasi-to-chunar",
    fromCity: "Varanasi",
    toCity: "Chunar",
    distance: 40,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "varanasi-to-jaunpur",
    fromCity: "Varanasi",
    toCity: "Jaunpur",
    distance: 60,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "varanasi-to-ghazipur",
    fromCity: "Varanasi",
    toCity: "Ghazipur",
    distance: 75,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "varanasi-to-ramnagar",
    fromCity: "Varanasi",
    toCity: "Ramnagar",
    distance: 15,
    duration: "30 - 45 min",
  },

  {
    slug: "varanasi-to-patna",
    fromCity: "Varanasi",
    toCity: "Patna",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "varanasi-to-bodh-gaya",
    fromCity: "Varanasi",
    toCity: "Bodh Gaya",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "varanasi-to-rajgir",
    fromCity: "Varanasi",
    toCity: "Rajgir",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "varanasi-to-nalanda",
    fromCity: "Varanasi",
    toCity: "Nalanda",
    distance: 270,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "varanasi-to-deoghar",
    fromCity: "Varanasi",
    toCity: "Deoghar",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "varanasi-to-jabalpur",
    fromCity: "Varanasi",
    toCity: "Jabalpur",
    distance: 350,
    duration: "7 - 8 hrs",
  },
  {
    slug: "varanasi-to-khajuraho",
    fromCity: "Varanasi",
    toCity: "Khajuraho",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "varanasi-to-rewa",
    fromCity: "Varanasi",
    toCity: "Rewa",
    distance: 180,
    duration: "4 - 5 hrs",
  },
  {
    slug: "varanasi-to-satna",
    fromCity: "Varanasi",
    toCity: "Satna",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "varanasi-to-azamgarh",
    fromCity: "Varanasi",
    toCity: "Azamgarh",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "varanasi-to-mau",
    fromCity: "Varanasi",
    toCity: "Mau",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "varanasi-to-ballia",
    fromCity: "Varanasi",
    toCity: "Ballia",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "varanasi-to-kushinagar",
    fromCity: "Varanasi",
    toCity: "Kushinagar",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "varanasi-to-lumbini",
    fromCity: "Varanasi",
    toCity: "Lumbini",
    distance: 260,
    duration: "6 - 7 hrs",
  },
  {
    slug: "varanasi-to-basti",
    fromCity: "Varanasi",
    toCity: "Basti",
    distance: 180,
    duration: "4 - 5 hrs",
  },
  {
    slug: "varanasi-to-siddharthnagar",
    fromCity: "Varanasi",
    toCity: "Siddharthnagar",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "varanasi-to-deoria",
    fromCity: "Varanasi",
    toCity: "Deoria",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "varanasi-to-lucknow",
    fromCity: "Varanasi",
    toCity: "Lucknow",
    distance: 320,
    duration: "6 - 7 hrs",
  },
  {
    slug: "varanasi-to-kanpur",
    fromCity: "Varanasi",
    toCity: "Kanpur",
    distance: 350,
    duration: "7 - 8 hrs",
  },
  {
    slug: "varanasi-to-agra",
    fromCity: "Varanasi",
    toCity: "Agra",
    distance: 600,
    duration: "10 - 12 hrs",
  },
  {
    slug: "varanasi-to-mathura",
    fromCity: "Varanasi",
    toCity: "Mathura",
    distance: 580,
    duration: "10 - 11 hrs",
  },
  {
    slug: "varanasi-to-vrindavan",
    fromCity: "Varanasi",
    toCity: "Vrindavan",
    distance: 585,
    duration: "10 - 11 hrs",
  },
  {
    slug: "varanasi-to-delhi",
    fromCity: "Varanasi",
    toCity: "Delhi",
    distance: 800,
    duration: "12 - 14 hrs",
  },
  {
    slug: "varanasi-to-noida",
    fromCity: "Varanasi",
    toCity: "Noida",
    distance: 810,
    duration: "13 - 15 hrs",
  },
  {
    slug: "varanasi-to-chitrakoot",
    fromCity: "Varanasi",
    toCity: "Chitrakoot",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "varanasi-to-robertsganj",
    fromCity: "Varanasi",
    toCity: "Robertsganj",
    distance: 130,
    duration: "3 - 4 hrs",
  },
  {
    slug: "varanasi-to-chopan",
    fromCity: "Varanasi",
    toCity: "Chopan",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "varanasi-to-buxar",
    fromCity: "Varanasi",
    toCity: "Buxar",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "varanasi-to-sasaram",
    fromCity: "Varanasi",
    toCity: "Sasaram",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "varanasi-to-arrah",
    fromCity: "Varanasi",
    toCity: "Arrah",
    distance: 180,
    duration: "4 - 5 hrs",
  },
  {
    slug: "varanasi-to-chapra",
    fromCity: "Varanasi",
    toCity: "Chapra",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "varanasi-to-muzaffarpur",
    fromCity: "Varanasi",
    toCity: "Muzaffarpur",
    distance: 300,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "varanasi-to-darbhanga",
    fromCity: "Varanasi",
    toCity: "Darbhanga",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "varanasi-to-ranchi",
    fromCity: "Varanasi",
    toCity: "Ranchi",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "varanasi-to-dhanbad",
    fromCity: "Varanasi",
    toCity: "Dhanbad",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "varanasi-to-jamshedpur",
    fromCity: "Varanasi",
    toCity: "Jamshedpur",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "varanasi-to-hazaribagh",
    fromCity: "Varanasi",
    toCity: "Hazaribagh",
    distance: 320,
    duration: "7 - 8 hrs",
  },
  {
    slug: "varanasi-to-kolkata",
    fromCity: "Varanasi",
    toCity: "Kolkata",
    distance: 680,
    duration: "12 - 14 hrs",
  },
  {
    slug: "varanasi-to-bhubaneswar",
    fromCity: "Varanasi",
    toCity: "Bhubaneswar",
    distance: 650,
    duration: "12 - 14 hrs",
  },

  // --- Ayodhya Nearby Routes ---
  {
    slug: "ayodhya-to-gorakhpur",
    fromCity: "Ayodhya",
    toCity: "Gorakhpur",
    distance: 135,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "ayodhya-to-prayagraj",
    fromCity: "Ayodhya",
    toCity: "Prayagraj",
    distance: 165,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "ayodhya-to-shravasti",
    fromCity: "Ayodhya",
    toCity: "Shravasti",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-sultanpur",
    fromCity: "Ayodhya",
    toCity: "Sultanpur",
    distance: 85,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-lucknow",
    fromCity: "Ayodhya",
    toCity: "Lucknow",
    distance: 135,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "ayodhya-to-kanpur",
    fromCity: "Ayodhya",
    toCity: "Kanpur",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-naimisharanya",
    fromCity: "Ayodhya",
    toCity: "Naimisharanya",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "ayodhya-to-sitapur",
    fromCity: "Ayodhya",
    toCity: "Sitapur",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-amethi",
    fromCity: "Ayodhya",
    toCity: "Amethi",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "ayodhya-to-gonda",
    fromCity: "Ayodhya",
    toCity: "Gonda",
    distance: 60,
    duration: "1.5 hrs",
  },
  {
    slug: "ayodhya-to-chitrakoot",
    fromCity: "Ayodhya",
    toCity: "Chitrakoot",
    distance: 200,
    duration: "4.5 - 5 hrs",
  },

  {
    slug: "ayodhya-to-vrindavan",
    fromCity: "Ayodhya",
    toCity: "Vrindavan",
    distance: 390,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-delhi",
    fromCity: "Ayodhya",
    toCity: "Delhi",
    distance: 560,
    duration: "9 - 10 hrs",
  },
  {
    slug: "ayodhya-to-noida",
    fromCity: "Ayodhya",
    toCity: "Noida",
    distance: 570,
    duration: "10 - 11 hrs",
  },
  {
    slug: "ayodhya-to-agra",
    fromCity: "Ayodhya",
    toCity: "Agra",
    distance: 400,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-haridwar",
    fromCity: "Ayodhya",
    toCity: "Haridwar",
    distance: 680,
    duration: "12 - 13 hrs",
  },
  {
    slug: "ayodhya-to-rishikesh",
    fromCity: "Ayodhya",
    toCity: "Rishikesh",
    distance: 700,
    duration: "13 - 14 hrs",
  },
  {
    slug: "ayodhya-to-dehradun",
    fromCity: "Ayodhya",
    toCity: "Dehradun",
    distance: 720,
    duration: "13 - 14 hrs",
  },
  {
    slug: "ayodhya-to-nainital",
    fromCity: "Ayodhya",
    toCity: "Nainital",
    distance: 520,
    duration: "10 - 12 hrs",
  },
  {
    slug: "ayodhya-to-bareilly",
    fromCity: "Ayodhya",
    toCity: "Bareilly",
    distance: 280,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "ayodhya-to-moradabad",
    fromCity: "Ayodhya",
    toCity: "Moradabad",
    distance: 330,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "ayodhya-to-aligarh",
    fromCity: "Ayodhya",
    toCity: "Aligarh",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-jhansi",
    fromCity: "Ayodhya",
    toCity: "Jhansi",
    distance: 420,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-khajuraho",
    fromCity: "Ayodhya",
    toCity: "Khajuraho",
    distance: 320,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-orchha",
    fromCity: "Ayodhya",
    toCity: "Orchha",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "ayodhya-to-gwalior",
    fromCity: "Ayodhya",
    toCity: "Gwalior",
    distance: 480,
    duration: "9 - 10 hrs",
  },
  {
    slug: "ayodhya-to-bhopal",
    fromCity: "Ayodhya",
    toCity: "Bhopal",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "ayodhya-to-indore",
    fromCity: "Ayodhya",
    toCity: "Indore",
    distance: 800,
    duration: "14 - 16 hrs",
  },
  {
    slug: "ayodhya-to-jaipur",
    fromCity: "Ayodhya",
    toCity: "Jaipur",
    distance: 750,
    duration: "13 - 14 hrs",
  },
  {
    slug: "ayodhya-to-udaipur",
    fromCity: "Ayodhya",
    toCity: "Udaipur",
    distance: 950,
    duration: "16 - 18 hrs",
  },
  {
    slug: "ayodhya-to-patna",
    fromCity: "Ayodhya",
    toCity: "Patna",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "ayodhya-to-gaya",
    fromCity: "Ayodhya",
    toCity: "Gaya",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-bodh-gaya",
    fromCity: "Ayodhya",
    toCity: "Bodh Gaya",
    distance: 360,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-rajgir",
    fromCity: "Ayodhya",
    toCity: "Rajgir",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-nalanda",
    fromCity: "Ayodhya",
    toCity: "Nalanda",
    distance: 370,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-deoghar",
    fromCity: "Ayodhya",
    toCity: "Deoghar",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-ranchi",
    fromCity: "Ayodhya",
    toCity: "Ranchi",
    distance: 500,
    duration: "10 - 11 hrs",
  },
  {
    slug: "ayodhya-to-kolkata",
    fromCity: "Ayodhya",
    toCity: "Kolkata",
    distance: 650,
    duration: "12 - 14 hrs",
  },
  {
    slug: "ayodhya-to-kushinagar",
    fromCity: "Ayodhya",
    toCity: "Kushinagar",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-lumbini",
    fromCity: "Ayodhya",
    toCity: "Lumbini",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "ayodhya-to-basti",
    fromCity: "Ayodhya",
    toCity: "Basti",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-deoria",
    fromCity: "Ayodhya",
    toCity: "Deoria",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "ayodhya-to-azamgarh",
    fromCity: "Ayodhya",
    toCity: "Azamgarh",
    distance: 140,
    duration: "3 - 4 hrs",
  },
  {
    slug: "ayodhya-to-mau",
    fromCity: "Ayodhya",
    toCity: "Mau",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-ballia",
    fromCity: "Ayodhya",
    toCity: "Ballia",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "ayodhya-to-jaunpur",
    fromCity: "Ayodhya",
    toCity: "Jaunpur",
    distance: 170,
    duration: "4 - 5 hrs",
  },
  {
    slug: "ayodhya-to-ghazipur",
    fromCity: "Ayodhya",
    toCity: "Ghazipur",
    distance: 190,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "ayodhya-to-mirzapur",
    fromCity: "Ayodhya",
    toCity: "Mirzapur",
    distance: 230,
    duration: "5 - 6 hrs",
  },

  // --- Delhi & Noida Expanded Routes ---
  {
    slug: "delhi-to-agra",
    fromCity: "Delhi",
    toCity: "Agra",
    distance: 230,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "delhi-to-jaipur",
    fromCity: "Delhi",
    toCity: "Jaipur",
    distance: 280,
    duration: "5 - 5.5 hrs",
  },
  {
    slug: "delhi-to-chandigarh",
    fromCity: "Delhi",
    toCity: "Chandigarh",
    distance: 250,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "delhi-to-dehradun",
    fromCity: "Delhi",
    toCity: "Dehradun",
    distance: 250,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "delhi-to-gurugram",
    fromCity: "Delhi",
    toCity: "Gurugram",
    distance: 30,
    duration: "45 min - 1.5 hrs",
  },
  {
    slug: "noida-to-rishikesh",
    fromCity: "Noida",
    toCity: "Rishikesh",
    distance: 240,
    duration: "5 - 6 hrs",
  },
  {
    slug: "noida-to-gurugram",
    fromCity: "Noida",
    toCity: "Gurugram",
    distance: 45,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "noida-to-faridabad",
    fromCity: "Noida",
    toCity: "Faridabad",
    distance: 30,
    duration: "45 min - 1 hr",
  },
  {
    slug: "delhi-to-agra",
    fromCity: "Delhi",
    toCity: "Agra",
    distance: 233,
    duration: "3.5 hrs",
  },
  {
    slug: "mumbai-to-pune",
    fromCity: "Mumbai",
    toCity: "Pune",
    distance: 150,
    duration: "3 hrs",
  },
  {
    slug: "bengaluru-to-mysuru",
    fromCity: "Bengaluru",
    toCity: "Mysuru",
    distance: 145,
    duration: "3 hrs",
  },
  {
    slug: "chennai-to-puducherry",
    fromCity: "Chennai",
    toCity: "Puducherry",
    distance: 155,
    duration: "3 hrs",
  },
  {
    slug: "jaipur-to-udaipur",
    fromCity: "Jaipur",
    toCity: "Udaipur",
    distance: 395,
    duration: "6.5 hrs",
  },
  {
    slug: "kolkata-to-digha",
    fromCity: "Kolkata",
    toCity: "Digha",
    distance: 185,
    duration: "4 hrs",
  },
  {
    slug: "hyderabad-to-srisailam",
    fromCity: "Hyderabad",
    toCity: "Srisailam",
    distance: 215,
    duration: "5 hrs",
  },
  {
    slug: "ahmedabad-to-statue-of-unity",
    fromCity: "Ahmedabad",
    toCity: "Statue of Unity",
    distance: 200,
    duration: "4 hrs",
  },
  {
    slug: "dehradun-to-mussoorie",
    fromCity: "Dehradun",
    toCity: "Mussoorie",
    distance: 35,
    duration: "1 hr",
  },
  {
    slug: "kochi-to-munnar",
    fromCity: "Kochi",
    toCity: "Munnar",
    distance: 130,
    duration: "4 hrs",
  },
  {
    slug: "ayodhya-to-varanasi",
    fromCity: "Ayodhya",
    toCity: "Varanasi",
    distance: 210,
    duration: "4 - 5 hrs",
  },
  {
    slug: "delhi-to-ayodhya",
    fromCity: "Delhi",
    toCity: "Ayodhya",
    distance: 560,
    duration: "9 - 10 hrs",
  },
  {
    slug: "varanasi-to-gorakhpur",
    fromCity: "Varanasi",
    toCity: "Gorakhpur",
    distance: 195,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-mathura",
    fromCity: "Ayodhya",
    toCity: "Mathura",
    distance: 380,
    duration: "7 - 8 hrs",
  },

  // --- Lucknow Popular Routes ---
  {
    slug: "lucknow-to-kanpur",
    fromCity: "Lucknow",
    toCity: "Kanpur",
    distance: 80,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "lucknow-to-prayagraj",
    fromCity: "Lucknow",
    toCity: "Prayagraj",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "lucknow-to-agra",
    fromCity: "Lucknow",
    toCity: "Agra",
    distance: 330,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-gorakhpur",
    fromCity: "Lucknow",
    toCity: "Gorakhpur",
    distance: 260,
    duration: "5 - 6 hrs",
  },
  {
    slug: "lucknow-to-bareilly",
    fromCity: "Lucknow",
    toCity: "Bareilly",
    distance: 240,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "lucknow-to-meerut",
    fromCity: "Lucknow",
    toCity: "Meerut",
    distance: 450,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-aligarh",
    fromCity: "Lucknow",
    toCity: "Aligarh",
    distance: 320,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-jhansi",
    fromCity: "Lucknow",
    toCity: "Jhansi",
    distance: 300,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-moradabad",
    fromCity: "Lucknow",
    toCity: "Moradabad",
    distance: 320,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-ghaziabad",
    fromCity: "Lucknow",
    toCity: "Ghaziabad",
    distance: 480,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-delhi",
    fromCity: "Lucknow",
    toCity: "Delhi",
    distance: 550,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-noida",
    fromCity: "Lucknow",
    toCity: "Noida",
    distance: 560,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-mathura",
    fromCity: "Lucknow",
    toCity: "Mathura",
    distance: 370,
    duration: "7 - 8 hrs",
  },
  {
    slug: "lucknow-to-vrindavan",
    fromCity: "Lucknow",
    toCity: "Vrindavan",
    distance: 375,
    duration: "7 - 8 hrs",
  },
  {
    slug: "lucknow-to-haridwar",
    fromCity: "Lucknow",
    toCity: "Haridwar",
    distance: 480,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-rishikesh",
    fromCity: "Lucknow",
    toCity: "Rishikesh",
    distance: 500,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-dehradun",
    fromCity: "Lucknow",
    toCity: "Dehradun",
    distance: 520,
    duration: "10 - 11 hrs",
  },
  {
    slug: "lucknow-to-nainital",
    fromCity: "Lucknow",
    toCity: "Nainital",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-chitrakoot",
    fromCity: "Lucknow",
    toCity: "Chitrakoot",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "lucknow-to-vindhyachal",
    fromCity: "Lucknow",
    toCity: "Vindhyachal",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "lucknow-to-orchha",
    fromCity: "Lucknow",
    toCity: "Orchha",
    distance: 320,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "lucknow-to-sitapur",
    fromCity: "Lucknow",
    toCity: "Sitapur",
    distance: 90,
    duration: "2 hrs",
  },
  {
    slug: "lucknow-to-unnao",
    fromCity: "Lucknow",
    toCity: "Unnao",
    distance: 40,
    duration: "1 hr",
  },
  {
    slug: "lucknow-to-rae-bareli",
    fromCity: "Lucknow",
    toCity: "Rae Bareli",
    distance: 80,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "lucknow-to-sultanpur",
    fromCity: "Lucknow",
    toCity: "Sultanpur",
    distance: 110,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "lucknow-to-basti",
    fromCity: "Lucknow",
    toCity: "Basti",
    distance: 220,
    duration: "4.5 - 5 hrs",
  },
  {
    slug: "lucknow-to-gonda",
    fromCity: "Lucknow",
    toCity: "Gonda",
    distance: 130,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "lucknow-to-bahraich",
    fromCity: "Lucknow",
    toCity: "Bahraich",
    distance: 130,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "lucknow-to-lakhimpur-kheri",
    fromCity: "Lucknow",
    toCity: "Lakhimpur Kheri",
    distance: 140,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "lucknow-to-hardoi",
    fromCity: "Lucknow",
    toCity: "Hardoi",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "lucknow-to-shahjahanpur",
    fromCity: "Lucknow",
    toCity: "Shahjahanpur",
    distance: 180,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "lucknow-to-patna",
    fromCity: "Lucknow",
    toCity: "Patna",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-gaya",
    fromCity: "Lucknow",
    toCity: "Gaya",
    distance: 420,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-bodh-gaya",
    fromCity: "Lucknow",
    toCity: "Bodh Gaya",
    distance: 450,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-ranchi",
    fromCity: "Lucknow",
    toCity: "Ranchi",
    distance: 550,
    duration: "11 - 12 hrs",
  },
  {
    slug: "lucknow-to-jaipur",
    fromCity: "Lucknow",
    toCity: "Jaipur",
    distance: 550,
    duration: "10 - 11 hrs",
  },
  {
    slug: "lucknow-to-gwalior",
    fromCity: "Lucknow",
    toCity: "Gwalior",
    distance: 380,
    duration: "7 - 8 hrs",
  },
  {
    slug: "lucknow-to-bhopal",
    fromCity: "Lucknow",
    toCity: "Bhopal",
    distance: 600,
    duration: "11 - 12 hrs",
  },
  {
    slug: "lucknow-to-indore",
    fromCity: "Lucknow",
    toCity: "Indore",
    distance: 750,
    duration: "13 - 14 hrs",
  },
  {
    slug: "lucknow-to-kolkata",
    fromCity: "Lucknow",
    toCity: "Kolkata",
    distance: 950,
    duration: "16 - 18 hrs",
  },
  {
    slug: "lucknow-to-chandigarh",
    fromCity: "Lucknow",
    toCity: "Chandigarh",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "lucknow-to-mumbai",
    fromCity: "Lucknow",
    toCity: "Mumbai",
    distance: 1400,
    duration: "22 - 24 hrs",
  },
  {
    slug: "lucknow-to-pune",
    fromCity: "Lucknow",
    toCity: "Pune",
    distance: 1500,
    duration: "24 - 26 hrs",
  },
  {
    slug: "lucknow-to-bengaluru",
    fromCity: "Lucknow",
    toCity: "Bengaluru",
    distance: 1900,
    duration: "30 - 32 hrs",
  },
  {
    slug: "lucknow-to-hyderabad",
    fromCity: "Lucknow",
    toCity: "Hyderabad",
    distance: 1300,
    duration: "22 - 24 hrs",
  },
  {
    slug: "lucknow-to-ahmedabad",
    fromCity: "Lucknow",
    toCity: "Ahmedabad",
    distance: 1100,
    duration: "18 - 20 hrs",
  },
  {
    slug: "lucknow-to-khajuraho",
    fromCity: "Lucknow",
    toCity: "Khajuraho",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-farrukhabad",
    fromCity: "Lucknow",
    toCity: "Farrukhabad",
    distance: 180,
    duration: "3.5 - 4.5 hrs",
  },
    // --- Prayagraj Popular Routes ---
  {
    slug: "prayagraj-to-varanasi",
    fromCity: "Prayagraj",
    toCity: "Varanasi",
    distance: 120,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "prayagraj-to-ayodhya",
    fromCity: "Prayagraj",
    toCity: "Ayodhya",
    distance: 165,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-lucknow",
    fromCity: "Prayagraj",
    toCity: "Lucknow",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "prayagraj-to-kanpur",
    fromCity: "Prayagraj",
    toCity: "Kanpur",
    distance: 190,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-vindhyachal",
    fromCity: "Prayagraj",
    toCity: "Vindhyachal",
    distance: 85,
    duration: "2 hrs",
  },
  {
    slug: "prayagraj-to-mirzapur",
    fromCity: "Prayagraj",
    toCity: "Mirzapur",
    distance: 95,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-chitrakoot",
    fromCity: "Prayagraj",
    toCity: "Chitrakoot",
    distance: 130,
    duration: "3 hrs",
  },
  {
    slug: "prayagraj-to-jaunpur",
    fromCity: "Prayagraj",
    toCity: "Jaunpur",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-ghazipur",
    fromCity: "Prayagraj",
    toCity: "Ghazipur",
    distance: 150,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-satna",
    fromCity: "Prayagraj",
    toCity: "Satna",
    distance: 170,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-rewa",
    fromCity: "Prayagraj",
    toCity: "Rewa",
    distance: 210,
    duration: "4.5 - 5 hrs",
  },
  {
    slug: "prayagraj-to-jabalpur",
    fromCity: "Prayagraj",
    toCity: "Jabalpur",
    distance: 300,
    duration: "6 - 7 hrs",
  },
  {
    slug: "prayagraj-to-delhi",
    fromCity: "Prayagraj",
    toCity: "Delhi",
    distance: 650,
    duration: "11 - 12 hrs",
  },
  {
    slug: "prayagraj-to-noida",
    fromCity: "Prayagraj",
    toCity: "Noida",
    distance: 660,
    duration: "11 - 12 hrs",
  },
  {
    slug: "prayagraj-to-agra",
    fromCity: "Prayagraj",
    toCity: "Agra",
    distance: 420,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "prayagraj-to-mathura",
    fromCity: "Prayagraj",
    toCity: "Mathura",
    distance: 440,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-vrindavan",
    fromCity: "Prayagraj",
    toCity: "Vrindavan",
    distance: 445,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-patna",
    fromCity: "Prayagraj",
    toCity: "Patna",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "prayagraj-to-gaya",
    fromCity: "Prayagraj",
    toCity: "Gaya",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-bodh-gaya",
    fromCity: "Prayagraj",
    toCity: "Bodh Gaya",
    distance: 410,
    duration: "8.5 - 9.5 hrs",
  },
  {
    slug: "prayagraj-to-gorakhpur",
    fromCity: "Prayagraj",
    toCity: "Gorakhpur",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "prayagraj-to-basti",
    fromCity: "Prayagraj",
    toCity: "Basti",
    distance: 260,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "prayagraj-to-azamgarh",
    fromCity: "Prayagraj",
    toCity: "Azamgarh",
    distance: 170,
    duration: "4 - 5 hrs",
  },
  {
    slug: "prayagraj-to-mau",
    fromCity: "Prayagraj",
    toCity: "Mau",
    distance: 190,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "prayagraj-to-ballia",
    fromCity: "Prayagraj",
    toCity: "Ballia",
    distance: 210,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-sultanpur",
    fromCity: "Prayagraj",
    toCity: "Sultanpur",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "prayagraj-to-amethi",
    fromCity: "Prayagraj",
    toCity: "Amethi",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-rae-bareli",
    fromCity: "Prayagraj",
    toCity: "Rae Bareli",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "prayagraj-to-fatehpur",
    fromCity: "Prayagraj",
    toCity: "Fatehpur",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-banda",
    fromCity: "Prayagraj",
    toCity: "Banda",
    distance: 140,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "prayagraj-to-jhansi",
    fromCity: "Prayagraj",
    toCity: "Jhansi",
    distance: 280,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "prayagraj-to-khajuraho",
    fromCity: "Prayagraj",
    toCity: "Khajuraho",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-orchha",
    fromCity: "Prayagraj",
    toCity: "Orchha",
    distance: 300,
    duration: "6 - 7 hrs",
  },
  {
    slug: "prayagraj-to-gwalior",
    fromCity: "Prayagraj",
    toCity: "Gwalior",
    distance: 380,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "prayagraj-to-bhopal",
    fromCity: "Prayagraj",
    toCity: "Bhopal",
    distance: 550,
    duration: "10 - 11 hrs",
  },
  {
    slug: "prayagraj-to-indore",
    fromCity: "Prayagraj",
    toCity: "Indore",
    distance: 700,
    duration: "13 - 14 hrs",
  },
  {
    slug: "prayagraj-to-jaipur",
    fromCity: "Prayagraj",
    toCity: "Jaipur",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "prayagraj-to-haridwar",
    fromCity: "Prayagraj",
    toCity: "Haridwar",
    distance: 750,
    duration: "14 - 15 hrs",
  },
  {
    slug: "prayagraj-to-rishikesh",
    fromCity: "Prayagraj",
    toCity: "Rishikesh",
    distance: 770,
    duration: "14 - 15 hrs",
  },
  {
    slug: "prayagraj-to-dehradun",
    fromCity: "Prayagraj",
    toCity: "Dehradun",
    distance: 790,
    duration: "15 - 16 hrs",
  },
  {
    slug: "prayagraj-to-nainital",
    fromCity: "Prayagraj",
    toCity: "Nainital",
    distance: 600,
    duration: "12 - 13 hrs",
  },
  {
    slug: "prayagraj-to-kolkata",
    fromCity: "Prayagraj",
    toCity: "Kolkata",
    distance: 750,
    duration: "14 - 15 hrs",
  },
  {
    slug: "prayagraj-to-ranchi",
    fromCity: "Prayagraj",
    toCity: "Ranchi",
    distance: 450,
    duration: "9 - 10 hrs",
  },
  {
    slug: "prayagraj-to-deoghar",
    fromCity: "Prayagraj",
    toCity: "Deoghar",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-buxar",
    fromCity: "Prayagraj",
    toCity: "Buxar",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "prayagraj-to-sasaram",
    fromCity: "Prayagraj",
    toCity: "Sasaram",
    distance: 230,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-muzaffarpur",
    fromCity: "Prayagraj",
    toCity: "Muzaffarpur",
    distance: 400,
    duration: "8.5 - 9.5 hrs",
  },
  {
    slug: "prayagraj-to-darbhanga",
    fromCity: "Prayagraj",
    toCity: "Darbhanga",
    distance: 430,
    duration: "9 - 10 hrs",
  },
  {
    slug: "prayagraj-to-gurugram",
    fromCity: "Prayagraj",
    toCity: "Gurugram",
    distance: 670,
    duration: "11.5 - 12.5 hrs",
  },
  {
    slug: "prayagraj-to-bareilly",
    fromCity: "Prayagraj",
    toCity: "Bareilly",
    distance: 350,
    duration: "7 - 8 hrs",
  },
];
