export type Route = {
  slug: string;
  fromCity: string;
  toCity: string;
  distance: number;
  duration: string;
};

export const ROUTES: Route[] = [
  // --- Existing Core Routes ---
  {
    slug: "noida-to-delhi",
    fromCity: "Noida",
    toCity: "Delhi",
    distance: 25,
    duration: "45 min - 1.5 hrs",
  },
  {
    slug: "lucknow-to-ayodhya",
    fromCity: "Lucknow",
    toCity: "Ayodhya",
    distance: 135,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "noida-to-agra",
    fromCity: "Noida",
    toCity: "Agra",
    distance: 200,
    duration: "4 - 5 hrs",
  },
  {
    slug: "noida-to-jaipur",
    fromCity: "Noida",
    toCity: "Jaipur",
    distance: 280,
    duration: "5 - 6 hrs",
  },
  {
    slug: "noida-to-haridwar",
    fromCity: "Noida",
    toCity: "Haridwar",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "noida-to-mathura",
    fromCity: "Noida",
    toCity: "Mathura",
    distance: 160,
    duration: "3 - 4 hrs",
  },
  {
    slug: "noida-to-vrindavan",
    fromCity: "Noida",
    toCity: "Vrindavan",
    distance: 165,
    duration: "3 - 4 hrs",
  },
  {
    slug: "lucknow-to-varanasi",
    fromCity: "Lucknow",
    toCity: "Varanasi",
    distance: 320,
    duration: "6 - 7 hrs",
  },

  // --- Routes TO Varanasi ---

  // --- Routes FROM Varanasi ---

  {
    slug: "varanasi-to-prayagraj",
    fromCity: "Varanasi",
    toCity: "Prayagraj",
    distance: 120,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "varanasi-to-sarnath",
    fromCity: "Varanasi",
    toCity: "Sarnath",
    distance: 10,
    duration: "20 - 30 min",
  },

  {
    slug: "varanasi-to-mirzapur",
    fromCity: "Varanasi",
    toCity: "Mirzapur",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "varanasi-to-ayodhya",
    fromCity: "Varanasi",
    toCity: "Ayodhya",
    distance: 200,
    duration: "4 - 5 hrs",
  },

  {
    slug: "varanasi-to-gaya",
    fromCity: "Varanasi",
    toCity: "Gaya",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "varanasi-to-vindhyachal",
    fromCity: "Varanasi",
    toCity: "Vindhyachal",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "varanasi-to-chunar",
    fromCity: "Varanasi",
    toCity: "Chunar",
    distance: 40,
    duration: "1 - 1.5 hrs",
  },

  {
    slug: "varanasi-to-jaunpur",
    fromCity: "Varanasi",
    toCity: "Jaunpur",
    distance: 60,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "varanasi-to-ghazipur",
    fromCity: "Varanasi",
    toCity: "Ghazipur",
    distance: 75,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "varanasi-to-ramnagar",
    fromCity: "Varanasi",
    toCity: "Ramnagar",
    distance: 15,
    duration: "30 - 45 min",
  },

  {
    slug: "varanasi-to-patna",
    fromCity: "Varanasi",
    toCity: "Patna",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "varanasi-to-bodh-gaya",
    fromCity: "Varanasi",
    toCity: "Bodh Gaya",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "varanasi-to-rajgir",
    fromCity: "Varanasi",
    toCity: "Rajgir",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "varanasi-to-nalanda",
    fromCity: "Varanasi",
    toCity: "Nalanda",
    distance: 270,
    duration: "5.5 - 6.5 hrs",
  },

  {
    slug: "varanasi-to-deoghar",
    fromCity: "Varanasi",
    toCity: "Deoghar",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "varanasi-to-jabalpur",
    fromCity: "Varanasi",
    toCity: "Jabalpur",
    distance: 350,
    duration: "7 - 8 hrs",
  },

  {
    slug: "varanasi-to-khajuraho",
    fromCity: "Varanasi",
    toCity: "Khajuraho",
    distance: 380,
    duration: "8 - 9 hrs",
  },

  {
    slug: "varanasi-to-rewa",
    fromCity: "Varanasi",
    toCity: "Rewa",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "varanasi-to-satna",
    fromCity: "Varanasi",
    toCity: "Satna",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "varanasi-to-azamgarh",
    fromCity: "Varanasi",
    toCity: "Azamgarh",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "varanasi-to-mau",
    fromCity: "Varanasi",
    toCity: "Mau",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "varanasi-to-ballia",
    fromCity: "Varanasi",
    toCity: "Ballia",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },

  {
    slug: "varanasi-to-kushinagar",
    fromCity: "Varanasi",
    toCity: "Kushinagar",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "varanasi-to-lumbini",
    fromCity: "Varanasi",
    toCity: "Lumbini",
    distance: 260,
    duration: "6 - 7 hrs",
  },

  {
    slug: "varanasi-to-basti",
    fromCity: "Varanasi",
    toCity: "Basti",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "varanasi-to-siddharthnagar",
    fromCity: "Varanasi",
    toCity: "Siddharthnagar",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "varanasi-to-deoria",
    fromCity: "Varanasi",
    toCity: "Deoria",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "varanasi-to-lucknow",
    fromCity: "Varanasi",
    toCity: "Lucknow",
    distance: 320,
    duration: "6 - 7 hrs",
  },

  {
    slug: "varanasi-to-kanpur",
    fromCity: "Varanasi",
    toCity: "Kanpur",
    distance: 350,
    duration: "7 - 8 hrs",
  },

  {
    slug: "varanasi-to-agra",
    fromCity: "Varanasi",
    toCity: "Agra",
    distance: 600,
    duration: "10 - 12 hrs",
  },

  {
    slug: "varanasi-to-mathura",
    fromCity: "Varanasi",
    toCity: "Mathura",
    distance: 580,
    duration: "10 - 11 hrs",
  },

  {
    slug: "varanasi-to-vrindavan",
    fromCity: "Varanasi",
    toCity: "Vrindavan",
    distance: 585,
    duration: "10 - 11 hrs",
  },

  {
    slug: "varanasi-to-delhi",
    fromCity: "Varanasi",
    toCity: "Delhi",
    distance: 800,
    duration: "12 - 14 hrs",
  },

  {
    slug: "varanasi-to-noida",
    fromCity: "Varanasi",
    toCity: "Noida",
    distance: 810,
    duration: "13 - 15 hrs",
  },

  {
    slug: "varanasi-to-chitrakoot",
    fromCity: "Varanasi",
    toCity: "Chitrakoot",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "varanasi-to-robertsganj",
    fromCity: "Varanasi",
    toCity: "Robertsganj",
    distance: 130,
    duration: "3 - 4 hrs",
  },

  {
    slug: "varanasi-to-chopan",
    fromCity: "Varanasi",
    toCity: "Chopan",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "varanasi-to-buxar",
    fromCity: "Varanasi",
    toCity: "Buxar",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },

  {
    slug: "varanasi-to-sasaram",
    fromCity: "Varanasi",
    toCity: "Sasaram",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "varanasi-to-arrah",
    fromCity: "Varanasi",
    toCity: "Arrah",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "varanasi-to-chapra",
    fromCity: "Varanasi",
    toCity: "Chapra",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "varanasi-to-muzaffarpur",
    fromCity: "Varanasi",
    toCity: "Muzaffarpur",
    distance: 300,
    duration: "6.5 - 7.5 hrs",
  },

  {
    slug: "varanasi-to-darbhanga",
    fromCity: "Varanasi",
    toCity: "Darbhanga",
    distance: 330,
    duration: "7 - 8 hrs",
  },

  {
    slug: "varanasi-to-ranchi",
    fromCity: "Varanasi",
    toCity: "Ranchi",
    distance: 400,
    duration: "8 - 9 hrs",
  },

  {
    slug: "varanasi-to-dhanbad",
    fromCity: "Varanasi",
    toCity: "Dhanbad",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "varanasi-to-jamshedpur",
    fromCity: "Varanasi",
    toCity: "Jamshedpur",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },

  {
    slug: "varanasi-to-hazaribagh",
    fromCity: "Varanasi",
    toCity: "Hazaribagh",
    distance: 320,
    duration: "7 - 8 hrs",
  },

  {
    slug: "varanasi-to-kolkata",
    fromCity: "Varanasi",
    toCity: "Kolkata",
    distance: 680,
    duration: "12 - 14 hrs",
  },

  {
    slug: "varanasi-to-bhubaneswar",
    fromCity: "Varanasi",
    toCity: "Bhubaneswar",
    distance: 650,
    duration: "12 - 14 hrs",
  },
  {
    slug: "prayagraj-to-varanasi",
    fromCity: "Prayagraj",
    toCity: "Varanasi",
    distance: 120,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "sarnath-to-varanasi",
    fromCity: "Sarnath",
    toCity: "Varanasi",
    distance: 10,
    duration: "20 - 30 min",
  },

  {
    slug: "mirzapur-to-varanasi",
    fromCity: "Mirzapur",
    toCity: "Varanasi",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "ayodhya-to-varanasi",
    fromCity: "Ayodhya",
    toCity: "Varanasi",
    distance: 200,
    duration: "4 - 5 hrs",
  },

  {
    slug: "gaya-to-varanasi",
    fromCity: "Gaya",
    toCity: "Varanasi",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "vindhyachal-to-varanasi",
    fromCity: "Vindhyachal",
    toCity: "Varanasi",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "chunar-to-varanasi",
    fromCity: "Chunar",
    toCity: "Varanasi",
    distance: 40,
    duration: "1 - 1.5 hrs",
  },

  {
    slug: "jaunpur-to-varanasi",
    fromCity: "Jaunpur",
    toCity: "Varanasi",
    distance: 60,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "ghazipur-to-varanasi",
    fromCity: "Ghazipur",
    toCity: "Varanasi",
    distance: 75,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "ramnagar-to-varanasi",
    fromCity: "Ramnagar",
    toCity: "Varanasi",
    distance: 15,
    duration: "30 - 45 min",
  },

  {
    slug: "patna-to-varanasi",
    fromCity: "Patna",
    toCity: "Varanasi",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "bodh-gaya-to-varanasi",
    fromCity: "Bodh Gaya",
    toCity: "Varanasi",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "rajgir-to-varanasi",
    fromCity: "Rajgir",
    toCity: "Varanasi",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "nalanda-to-varanasi",
    fromCity: "Nalanda",
    toCity: "Varanasi",
    distance: 270,
    duration: "5.5 - 6.5 hrs",
  },

  {
    slug: "deoghar-to-varanasi",
    fromCity: "Deoghar",
    toCity: "Varanasi",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "jabalpur-to-varanasi",
    fromCity: "Jabalpur",
    toCity: "Varanasi",
    distance: 350,
    duration: "7 - 8 hrs",
  },

  {
    slug: "khajuraho-to-varanasi",
    fromCity: "Khajuraho",
    toCity: "Varanasi",
    distance: 380,
    duration: "8 - 9 hrs",
  },

  {
    slug: "rewa-to-varanasi",
    fromCity: "Rewa",
    toCity: "Varanasi",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "satna-to-varanasi",
    fromCity: "Satna",
    toCity: "Varanasi",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "azamgarh-to-varanasi",
    fromCity: "Azamgarh",
    toCity: "Varanasi",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "mau-to-varanasi",
    fromCity: "Mau",
    toCity: "Varanasi",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "ballia-to-varanasi",
    fromCity: "Ballia",
    toCity: "Varanasi",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },

  {
    slug: "kushinagar-to-varanasi",
    fromCity: "Kushinagar",
    toCity: "Varanasi",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "lumbini-to-varanasi",
    fromCity: "Lumbini",
    toCity: "Varanasi",
    distance: 260,
    duration: "6 - 7 hrs",
  },

  {
    slug: "basti-to-varanasi",
    fromCity: "Basti",
    toCity: "Varanasi",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "siddharthnagar-to-varanasi",
    fromCity: "Siddharthnagar",
    toCity: "Varanasi",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "deoria-to-varanasi",
    fromCity: "Deoria",
    toCity: "Varanasi",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "lucknow-to-varanasi",
    fromCity: "Lucknow",
    toCity: "Varanasi",
    distance: 320,
    duration: "6 - 7 hrs",
  },

  {
    slug: "kanpur-to-varanasi",
    fromCity: "Kanpur",
    toCity: "Varanasi",
    distance: 350,
    duration: "7 - 8 hrs",
  },

  {
    slug: "agra-to-varanasi",
    fromCity: "Agra",
    toCity: "Varanasi",
    distance: 600,
    duration: "10 - 12 hrs",
  },

  {
    slug: "mathura-to-varanasi",
    fromCity: "Mathura",
    toCity: "Varanasi",
    distance: 580,
    duration: "10 - 11 hrs",
  },

  {
    slug: "vrindavan-to-varanasi",
    fromCity: "Vrindavan",
    toCity: "Varanasi",
    distance: 585,
    duration: "10 - 11 hrs",
  },

  {
    slug: "delhi-to-varanasi",
    fromCity: "Delhi",
    toCity: "Varanasi",
    distance: 800,
    duration: "12 - 14 hrs",
  },

  {
    slug: "noida-to-varanasi",
    fromCity: "Noida",
    toCity: "Varanasi",
    distance: 810,
    duration: "13 - 15 hrs",
  },

  {
    slug: "chitrakoot-to-varanasi",
    fromCity: "Chitrakoot",
    toCity: "Varanasi",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "robertsganj-to-varanasi",
    fromCity: "Robertsganj",
    toCity: "Varanasi",
    distance: 130,
    duration: "3 - 4 hrs",
  },

  {
    slug: "chopan-to-varanasi",
    fromCity: "Chopan",
    toCity: "Varanasi",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "buxar-to-varanasi",
    fromCity: "Buxar",
    toCity: "Varanasi",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },

  {
    slug: "sasaram-to-varanasi",
    fromCity: "Sasaram",
    toCity: "Varanasi",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "arrah-to-varanasi",
    fromCity: "Arrah",
    toCity: "Varanasi",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "chapra-to-varanasi",
    fromCity: "Chapra",
    toCity: "Varanasi",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "muzaffarpur-to-varanasi",
    fromCity: "Muzaffarpur",
    toCity: "Varanasi",
    distance: 300,
    duration: "6.5 - 7.5 hrs",
  },

  {
    slug: "darbhanga-to-varanasi",
    fromCity: "Darbhanga",
    toCity: "Varanasi",
    distance: 330,
    duration: "7 - 8 hrs",
  },

  {
    slug: "ranchi-to-varanasi",
    fromCity: "Ranchi",
    toCity: "Varanasi",
    distance: 400,
    duration: "8 - 9 hrs",
  },

  {
    slug: "dhanbad-to-varanasi",
    fromCity: "Dhanbad",
    toCity: "Varanasi",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "jamshedpur-to-varanasi",
    fromCity: "Jamshedpur",
    toCity: "Varanasi",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },

  {
    slug: "hazaribagh-to-varanasi",
    fromCity: "Hazaribagh",
    toCity: "Varanasi",
    distance: 320,
    duration: "7 - 8 hrs",
  },

  {
    slug: "kolkata-to-varanasi",
    fromCity: "Kolkata",
    toCity: "Varanasi",
    distance: 680,
    duration: "12 - 14 hrs",
  },

  {
    slug: "bhubaneswar-to-varanasi",
    fromCity: "Bhubaneswar",
    toCity: "Varanasi",
    distance: 650,
    duration: "12 - 14 hrs",
  },
  // --- Ayodhya Nearby Routes ---
  {
    slug: "ayodhya-to-gorakhpur",
    fromCity: "Ayodhya",
    toCity: "Gorakhpur",
    distance: 135,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "ayodhya-to-prayagraj",
    fromCity: "Ayodhya",
    toCity: "Prayagraj",
    distance: 165,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "ayodhya-to-shravasti",
    fromCity: "Ayodhya",
    toCity: "Shravasti",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-sultanpur",
    fromCity: "Ayodhya",
    toCity: "Sultanpur",
    distance: 85,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-lucknow",
    fromCity: "Ayodhya",
    toCity: "Lucknow",
    distance: 135,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "ayodhya-to-kanpur",
    fromCity: "Ayodhya",
    toCity: "Kanpur",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-naimisharanya",
    fromCity: "Ayodhya",
    toCity: "Naimisharanya",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "ayodhya-to-sitapur",
    fromCity: "Ayodhya",
    toCity: "Sitapur",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-amethi",
    fromCity: "Ayodhya",
    toCity: "Amethi",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "ayodhya-to-gonda",
    fromCity: "Ayodhya",
    toCity: "Gonda",
    distance: 60,
    duration: "1.5 hrs",
  },
  {
    slug: "ayodhya-to-chitrakoot",
    fromCity: "Ayodhya",
    toCity: "Chitrakoot",
    distance: 200,
    duration: "4.5 - 5 hrs",
  },

  {
    slug: "ayodhya-to-vrindavan",
    fromCity: "Ayodhya",
    toCity: "Vrindavan",
    distance: 390,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-delhi",
    fromCity: "Ayodhya",
    toCity: "Delhi",
    distance: 560,
    duration: "9 - 10 hrs",
  },
  {
    slug: "ayodhya-to-noida",
    fromCity: "Ayodhya",
    toCity: "Noida",
    distance: 570,
    duration: "10 - 11 hrs",
  },
  {
    slug: "ayodhya-to-agra",
    fromCity: "Ayodhya",
    toCity: "Agra",
    distance: 400,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-haridwar",
    fromCity: "Ayodhya",
    toCity: "Haridwar",
    distance: 680,
    duration: "12 - 13 hrs",
  },
  {
    slug: "ayodhya-to-rishikesh",
    fromCity: "Ayodhya",
    toCity: "Rishikesh",
    distance: 700,
    duration: "13 - 14 hrs",
  },
  {
    slug: "ayodhya-to-dehradun",
    fromCity: "Ayodhya",
    toCity: "Dehradun",
    distance: 720,
    duration: "13 - 14 hrs",
  },
  {
    slug: "ayodhya-to-nainital",
    fromCity: "Ayodhya",
    toCity: "Nainital",
    distance: 520,
    duration: "10 - 12 hrs",
  },
  {
    slug: "ayodhya-to-bareilly",
    fromCity: "Ayodhya",
    toCity: "Bareilly",
    distance: 280,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "ayodhya-to-moradabad",
    fromCity: "Ayodhya",
    toCity: "Moradabad",
    distance: 330,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "ayodhya-to-aligarh",
    fromCity: "Ayodhya",
    toCity: "Aligarh",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-jhansi",
    fromCity: "Ayodhya",
    toCity: "Jhansi",
    distance: 420,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-khajuraho",
    fromCity: "Ayodhya",
    toCity: "Khajuraho",
    distance: 320,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-orchha",
    fromCity: "Ayodhya",
    toCity: "Orchha",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "ayodhya-to-gwalior",
    fromCity: "Ayodhya",
    toCity: "Gwalior",
    distance: 480,
    duration: "9 - 10 hrs",
  },
  {
    slug: "ayodhya-to-bhopal",
    fromCity: "Ayodhya",
    toCity: "Bhopal",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "ayodhya-to-indore",
    fromCity: "Ayodhya",
    toCity: "Indore",
    distance: 800,
    duration: "14 - 16 hrs",
  },
  {
    slug: "ayodhya-to-jaipur",
    fromCity: "Ayodhya",
    toCity: "Jaipur",
    distance: 750,
    duration: "13 - 14 hrs",
  },
  {
    slug: "ayodhya-to-udaipur",
    fromCity: "Ayodhya",
    toCity: "Udaipur",
    distance: 950,
    duration: "16 - 18 hrs",
  },
  {
    slug: "ayodhya-to-patna",
    fromCity: "Ayodhya",
    toCity: "Patna",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "ayodhya-to-gaya",
    fromCity: "Ayodhya",
    toCity: "Gaya",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "ayodhya-to-bodh-gaya",
    fromCity: "Ayodhya",
    toCity: "Bodh Gaya",
    distance: 360,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-rajgir",
    fromCity: "Ayodhya",
    toCity: "Rajgir",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-nalanda",
    fromCity: "Ayodhya",
    toCity: "Nalanda",
    distance: 370,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-deoghar",
    fromCity: "Ayodhya",
    toCity: "Deoghar",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-ranchi",
    fromCity: "Ayodhya",
    toCity: "Ranchi",
    distance: 500,
    duration: "10 - 11 hrs",
  },
  {
    slug: "ayodhya-to-kolkata",
    fromCity: "Ayodhya",
    toCity: "Kolkata",
    distance: 650,
    duration: "12 - 14 hrs",
  },
  {
    slug: "ayodhya-to-kushinagar",
    fromCity: "Ayodhya",
    toCity: "Kushinagar",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-lumbini",
    fromCity: "Ayodhya",
    toCity: "Lumbini",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "ayodhya-to-basti",
    fromCity: "Ayodhya",
    toCity: "Basti",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "ayodhya-to-deoria",
    fromCity: "Ayodhya",
    toCity: "Deoria",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "ayodhya-to-azamgarh",
    fromCity: "Ayodhya",
    toCity: "Azamgarh",
    distance: 140,
    duration: "3 - 4 hrs",
  },
  {
    slug: "ayodhya-to-mau",
    fromCity: "Ayodhya",
    toCity: "Mau",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-ballia",
    fromCity: "Ayodhya",
    toCity: "Ballia",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "ayodhya-to-jaunpur",
    fromCity: "Ayodhya",
    toCity: "Jaunpur",
    distance: 170,
    duration: "4 - 5 hrs",
  },
  {
    slug: "ayodhya-to-ghazipur",
    fromCity: "Ayodhya",
    toCity: "Ghazipur",
    distance: 190,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "ayodhya-to-mirzapur",
    fromCity: "Ayodhya",
    toCity: "Mirzapur",
    distance: 230,
    duration: "5 - 6 hrs",
  },

  // --- Delhi & Noida Expanded Routes ---
  {
    slug: "delhi-to-agra",
    fromCity: "Delhi",
    toCity: "Agra",
    distance: 230,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "delhi-to-jaipur",
    fromCity: "Delhi",
    toCity: "Jaipur",
    distance: 280,
    duration: "5 - 5.5 hrs",
  },
  {
    slug: "delhi-to-chandigarh",
    fromCity: "Delhi",
    toCity: "Chandigarh",
    distance: 250,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "delhi-to-dehradun",
    fromCity: "Delhi",
    toCity: "Dehradun",
    distance: 250,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "delhi-to-gurugram",
    fromCity: "Delhi",
    toCity: "Gurugram",
    distance: 30,
    duration: "45 min - 1.5 hrs",
  },
  {
    slug: "noida-to-rishikesh",
    fromCity: "Noida",
    toCity: "Rishikesh",
    distance: 240,
    duration: "5 - 6 hrs",
  },
  {
    slug: "noida-to-gurugram",
    fromCity: "Noida",
    toCity: "Gurugram",
    distance: 45,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "noida-to-faridabad",
    fromCity: "Noida",
    toCity: "Faridabad",
    distance: 30,
    duration: "45 min - 1 hr",
  },
  {
    slug: "delhi-to-agra",
    fromCity: "Delhi",
    toCity: "Agra",
    distance: 233,
    duration: "3.5 hrs",
  },
  {
    slug: "mumbai-to-pune",
    fromCity: "Mumbai",
    toCity: "Pune",
    distance: 150,
    duration: "3 hrs",
  },
  {
    slug: "bengaluru-to-mysuru",
    fromCity: "Bengaluru",
    toCity: "Mysuru",
    distance: 145,
    duration: "3 hrs",
  },
  {
    slug: "chennai-to-puducherry",
    fromCity: "Chennai",
    toCity: "Puducherry",
    distance: 155,
    duration: "3 hrs",
  },
  {
    slug: "jaipur-to-udaipur",
    fromCity: "Jaipur",
    toCity: "Udaipur",
    distance: 395,
    duration: "6.5 hrs",
  },
  {
    slug: "kolkata-to-digha",
    fromCity: "Kolkata",
    toCity: "Digha",
    distance: 185,
    duration: "4 hrs",
  },
  {
    slug: "hyderabad-to-srisailam",
    fromCity: "Hyderabad",
    toCity: "Srisailam",
    distance: 215,
    duration: "5 hrs",
  },
  {
    slug: "ahmedabad-to-statue-of-unity",
    fromCity: "Ahmedabad",
    toCity: "Statue of Unity",
    distance: 200,
    duration: "4 hrs",
  },
  {
    slug: "dehradun-to-mussoorie",
    fromCity: "Dehradun",
    toCity: "Mussoorie",
    distance: 35,
    duration: "1 hr",
  },
  {
    slug: "kochi-to-munnar",
    fromCity: "Kochi",
    toCity: "Munnar",
    distance: 130,
    duration: "4 hrs",
  },
  {
    slug: "ayodhya-to-varanasi",
    fromCity: "Ayodhya",
    toCity: "Varanasi",
    distance: 210,
    duration: "4 - 5 hrs",
  },
  {
    slug: "delhi-to-ayodhya",
    fromCity: "Delhi",
    toCity: "Ayodhya",
    distance: 560,
    duration: "9 - 10 hrs",
  },
  {
    slug: "varanasi-to-gorakhpur",
    fromCity: "Varanasi",
    toCity: "Gorakhpur",
    distance: 195,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "ayodhya-to-mathura",
    fromCity: "Ayodhya",
    toCity: "Mathura",
    distance: 380,
    duration: "7 - 8 hrs",
  },

  // --- Lucknow Popular Routes ---
  {
    slug: "lucknow-to-kanpur",
    fromCity: "Lucknow",
    toCity: "Kanpur",
    distance: 80,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "lucknow-to-prayagraj",
    fromCity: "Lucknow",
    toCity: "Prayagraj",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "lucknow-to-agra",
    fromCity: "Lucknow",
    toCity: "Agra",
    distance: 330,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-gorakhpur",
    fromCity: "Lucknow",
    toCity: "Gorakhpur",
    distance: 260,
    duration: "5 - 6 hrs",
  },
  {
    slug: "lucknow-to-bareilly",
    fromCity: "Lucknow",
    toCity: "Bareilly",
    distance: 240,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "lucknow-to-meerut",
    fromCity: "Lucknow",
    toCity: "Meerut",
    distance: 450,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-aligarh",
    fromCity: "Lucknow",
    toCity: "Aligarh",
    distance: 320,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-jhansi",
    fromCity: "Lucknow",
    toCity: "Jhansi",
    distance: 300,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-moradabad",
    fromCity: "Lucknow",
    toCity: "Moradabad",
    distance: 320,
    duration: "6 - 7 hrs",
  },
  {
    slug: "lucknow-to-ghaziabad",
    fromCity: "Lucknow",
    toCity: "Ghaziabad",
    distance: 480,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-delhi",
    fromCity: "Lucknow",
    toCity: "Delhi",
    distance: 550,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-noida",
    fromCity: "Lucknow",
    toCity: "Noida",
    distance: 560,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-mathura",
    fromCity: "Lucknow",
    toCity: "Mathura",
    distance: 370,
    duration: "7 - 8 hrs",
  },
  {
    slug: "lucknow-to-vrindavan",
    fromCity: "Lucknow",
    toCity: "Vrindavan",
    distance: 375,
    duration: "7 - 8 hrs",
  },
  {
    slug: "lucknow-to-haridwar",
    fromCity: "Lucknow",
    toCity: "Haridwar",
    distance: 480,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-rishikesh",
    fromCity: "Lucknow",
    toCity: "Rishikesh",
    distance: 500,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-dehradun",
    fromCity: "Lucknow",
    toCity: "Dehradun",
    distance: 520,
    duration: "10 - 11 hrs",
  },
  {
    slug: "lucknow-to-nainital",
    fromCity: "Lucknow",
    toCity: "Nainital",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-chitrakoot",
    fromCity: "Lucknow",
    toCity: "Chitrakoot",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "lucknow-to-vindhyachal",
    fromCity: "Lucknow",
    toCity: "Vindhyachal",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "lucknow-to-orchha",
    fromCity: "Lucknow",
    toCity: "Orchha",
    distance: 320,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "lucknow-to-sitapur",
    fromCity: "Lucknow",
    toCity: "Sitapur",
    distance: 90,
    duration: "2 hrs",
  },
  {
    slug: "lucknow-to-unnao",
    fromCity: "Lucknow",
    toCity: "Unnao",
    distance: 40,
    duration: "1 hr",
  },
  {
    slug: "lucknow-to-rae-bareli",
    fromCity: "Lucknow",
    toCity: "Rae Bareli",
    distance: 80,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "lucknow-to-sultanpur",
    fromCity: "Lucknow",
    toCity: "Sultanpur",
    distance: 110,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "lucknow-to-basti",
    fromCity: "Lucknow",
    toCity: "Basti",
    distance: 220,
    duration: "4.5 - 5 hrs",
  },
  {
    slug: "lucknow-to-gonda",
    fromCity: "Lucknow",
    toCity: "Gonda",
    distance: 130,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "lucknow-to-bahraich",
    fromCity: "Lucknow",
    toCity: "Bahraich",
    distance: 130,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "lucknow-to-lakhimpur-kheri",
    fromCity: "Lucknow",
    toCity: "Lakhimpur Kheri",
    distance: 140,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "lucknow-to-hardoi",
    fromCity: "Lucknow",
    toCity: "Hardoi",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "lucknow-to-shahjahanpur",
    fromCity: "Lucknow",
    toCity: "Shahjahanpur",
    distance: 180,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "lucknow-to-patna",
    fromCity: "Lucknow",
    toCity: "Patna",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-gaya",
    fromCity: "Lucknow",
    toCity: "Gaya",
    distance: 420,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-bodh-gaya",
    fromCity: "Lucknow",
    toCity: "Bodh Gaya",
    distance: 450,
    duration: "9 - 10 hrs",
  },
  {
    slug: "lucknow-to-ranchi",
    fromCity: "Lucknow",
    toCity: "Ranchi",
    distance: 550,
    duration: "11 - 12 hrs",
  },
  {
    slug: "lucknow-to-jaipur",
    fromCity: "Lucknow",
    toCity: "Jaipur",
    distance: 550,
    duration: "10 - 11 hrs",
  },
  {
    slug: "lucknow-to-gwalior",
    fromCity: "Lucknow",
    toCity: "Gwalior",
    distance: 380,
    duration: "7 - 8 hrs",
  },
  {
    slug: "lucknow-to-bhopal",
    fromCity: "Lucknow",
    toCity: "Bhopal",
    distance: 600,
    duration: "11 - 12 hrs",
  },
  {
    slug: "lucknow-to-indore",
    fromCity: "Lucknow",
    toCity: "Indore",
    distance: 750,
    duration: "13 - 14 hrs",
  },
  {
    slug: "lucknow-to-kolkata",
    fromCity: "Lucknow",
    toCity: "Kolkata",
    distance: 950,
    duration: "16 - 18 hrs",
  },
  {
    slug: "lucknow-to-chandigarh",
    fromCity: "Lucknow",
    toCity: "Chandigarh",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "lucknow-to-mumbai",
    fromCity: "Lucknow",
    toCity: "Mumbai",
    distance: 1400,
    duration: "22 - 24 hrs",
  },
  {
    slug: "lucknow-to-pune",
    fromCity: "Lucknow",
    toCity: "Pune",
    distance: 1500,
    duration: "24 - 26 hrs",
  },
  {
    slug: "lucknow-to-bengaluru",
    fromCity: "Lucknow",
    toCity: "Bengaluru",
    distance: 1900,
    duration: "30 - 32 hrs",
  },
  {
    slug: "lucknow-to-hyderabad",
    fromCity: "Lucknow",
    toCity: "Hyderabad",
    distance: 1300,
    duration: "22 - 24 hrs",
  },
  {
    slug: "lucknow-to-ahmedabad",
    fromCity: "Lucknow",
    toCity: "Ahmedabad",
    distance: 1100,
    duration: "18 - 20 hrs",
  },
  {
    slug: "lucknow-to-khajuraho",
    fromCity: "Lucknow",
    toCity: "Khajuraho",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "lucknow-to-farrukhabad",
    fromCity: "Lucknow",
    toCity: "Farrukhabad",
    distance: 180,
    duration: "3.5 - 4.5 hrs",
  },



  // --- Prayagraj Popular Routes ---
  {
    slug: "prayagraj-to-varanasi",
    fromCity: "Prayagraj",
    toCity: "Varanasi",
    distance: 120,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "prayagraj-to-ayodhya",
    fromCity: "Prayagraj",
    toCity: "Ayodhya",
    distance: 165,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-lucknow",
    fromCity: "Prayagraj",
    toCity: "Lucknow",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "prayagraj-to-kanpur",
    fromCity: "Prayagraj",
    toCity: "Kanpur",
    distance: 190,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-vindhyachal",
    fromCity: "Prayagraj",
    toCity: "Vindhyachal",
    distance: 85,
    duration: "2 hrs",
  },
  {
    slug: "prayagraj-to-mirzapur",
    fromCity: "Prayagraj",
    toCity: "Mirzapur",
    distance: 95,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-chitrakoot",
    fromCity: "Prayagraj",
    toCity: "Chitrakoot",
    distance: 130,
    duration: "3 hrs",
  },
  {
    slug: "prayagraj-to-jaunpur",
    fromCity: "Prayagraj",
    toCity: "Jaunpur",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-ghazipur",
    fromCity: "Prayagraj",
    toCity: "Ghazipur",
    distance: 150,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-satna",
    fromCity: "Prayagraj",
    toCity: "Satna",
    distance: 170,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "prayagraj-to-rewa",
    fromCity: "Prayagraj",
    toCity: "Rewa",
    distance: 210,
    duration: "4.5 - 5 hrs",
  },
  {
    slug: "prayagraj-to-jabalpur",
    fromCity: "Prayagraj",
    toCity: "Jabalpur",
    distance: 300,
    duration: "6 - 7 hrs",
  },
  {
    slug: "prayagraj-to-delhi",
    fromCity: "Prayagraj",
    toCity: "Delhi",
    distance: 650,
    duration: "11 - 12 hrs",
  },
  {
    slug: "prayagraj-to-noida",
    fromCity: "Prayagraj",
    toCity: "Noida",
    distance: 660,
    duration: "11 - 12 hrs",
  },
  {
    slug: "prayagraj-to-agra",
    fromCity: "Prayagraj",
    toCity: "Agra",
    distance: 420,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "prayagraj-to-mathura",
    fromCity: "Prayagraj",
    toCity: "Mathura",
    distance: 440,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-vrindavan",
    fromCity: "Prayagraj",
    toCity: "Vrindavan",
    distance: 445,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-patna",
    fromCity: "Prayagraj",
    toCity: "Patna",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "prayagraj-to-gaya",
    fromCity: "Prayagraj",
    toCity: "Gaya",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-bodh-gaya",
    fromCity: "Prayagraj",
    toCity: "Bodh Gaya",
    distance: 410,
    duration: "8.5 - 9.5 hrs",
  },
  {
    slug: "prayagraj-to-gorakhpur",
    fromCity: "Prayagraj",
    toCity: "Gorakhpur",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "prayagraj-to-basti",
    fromCity: "Prayagraj",
    toCity: "Basti",
    distance: 260,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "prayagraj-to-azamgarh",
    fromCity: "Prayagraj",
    toCity: "Azamgarh",
    distance: 170,
    duration: "4 - 5 hrs",
  },
  {
    slug: "prayagraj-to-mau",
    fromCity: "Prayagraj",
    toCity: "Mau",
    distance: 190,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "prayagraj-to-ballia",
    fromCity: "Prayagraj",
    toCity: "Ballia",
    distance: 210,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-sultanpur",
    fromCity: "Prayagraj",
    toCity: "Sultanpur",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "prayagraj-to-amethi",
    fromCity: "Prayagraj",
    toCity: "Amethi",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-rae-bareli",
    fromCity: "Prayagraj",
    toCity: "Rae Bareli",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "prayagraj-to-fatehpur",
    fromCity: "Prayagraj",
    toCity: "Fatehpur",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "prayagraj-to-banda",
    fromCity: "Prayagraj",
    toCity: "Banda",
    distance: 140,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "prayagraj-to-jhansi",
    fromCity: "Prayagraj",
    toCity: "Jhansi",
    distance: 280,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "prayagraj-to-khajuraho",
    fromCity: "Prayagraj",
    toCity: "Khajuraho",
    distance: 250,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-orchha",
    fromCity: "Prayagraj",
    toCity: "Orchha",
    distance: 300,
    duration: "6 - 7 hrs",
  },
  {
    slug: "prayagraj-to-gwalior",
    fromCity: "Prayagraj",
    toCity: "Gwalior",
    distance: 380,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "prayagraj-to-bhopal",
    fromCity: "Prayagraj",
    toCity: "Bhopal",
    distance: 550,
    duration: "10 - 11 hrs",
  },
  {
    slug: "prayagraj-to-indore",
    fromCity: "Prayagraj",
    toCity: "Indore",
    distance: 700,
    duration: "13 - 14 hrs",
  },
  {
    slug: "prayagraj-to-jaipur",
    fromCity: "Prayagraj",
    toCity: "Jaipur",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "prayagraj-to-haridwar",
    fromCity: "Prayagraj",
    toCity: "Haridwar",
    distance: 750,
    duration: "14 - 15 hrs",
  },
  {
    slug: "prayagraj-to-rishikesh",
    fromCity: "Prayagraj",
    toCity: "Rishikesh",
    distance: 770,
    duration: "14 - 15 hrs",
  },
  {
    slug: "prayagraj-to-dehradun",
    fromCity: "Prayagraj",
    toCity: "Dehradun",
    distance: 790,
    duration: "15 - 16 hrs",
  },
  {
    slug: "prayagraj-to-nainital",
    fromCity: "Prayagraj",
    toCity: "Nainital",
    distance: 600,
    duration: "12 - 13 hrs",
  },
  {
    slug: "prayagraj-to-kolkata",
    fromCity: "Prayagraj",
    toCity: "Kolkata",
    distance: 750,
    duration: "14 - 15 hrs",
  },
  {
    slug: "prayagraj-to-ranchi",
    fromCity: "Prayagraj",
    toCity: "Ranchi",
    distance: 450,
    duration: "9 - 10 hrs",
  },
  {
    slug: "prayagraj-to-deoghar",
    fromCity: "Prayagraj",
    toCity: "Deoghar",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "prayagraj-to-buxar",
    fromCity: "Prayagraj",
    toCity: "Buxar",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "prayagraj-to-sasaram",
    fromCity: "Prayagraj",
    toCity: "Sasaram",
    distance: 230,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-muzaffarpur",
    fromCity: "Prayagraj",
    toCity: "Muzaffarpur",
    distance: 400,
    duration: "8.5 - 9.5 hrs",
  },
  {
    slug: "prayagraj-to-darbhanga",
    fromCity: "Prayagraj",
    toCity: "Darbhanga",
    distance: 430,
    duration: "9 - 10 hrs",
  },
  {
    slug: "prayagraj-to-gurugram",
    fromCity: "Prayagraj",
    toCity: "Gurugram",
    distance: 670,
    duration: "11.5 - 12.5 hrs",
  },
  {
    slug: "prayagraj-to-bareilly",
    fromCity: "Prayagraj",
    toCity: "Bareilly",
    distance: 350,
    duration: "7 - 8 hrs",
  },

  // --- Gaya Popular Routes ---


  {
    slug: "patna-to-gaya",
    fromCity: "Patna",
    toCity: "Gaya",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "bodh-gaya-to-gaya",
    fromCity: "Bodh Gaya",
    toCity: "Gaya",
    distance: 15,
    duration: "30 - 45 min",
  },
  {
    slug: "nalanda-to-gaya",
    fromCity: "Nalanda",
    toCity: "Gaya",
    distance: 85,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "rajgir-to-gaya",
    fromCity: "Rajgir",
    toCity: "Gaya",
    distance: 95,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "nawada-to-gaya",
    fromCity: "Nawada",
    toCity: "Gaya",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "jehanabad-to-gaya",
    fromCity: "Jehanabad",
    toCity: "Gaya",
    distance: 50,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "aurangabad-to-gaya",
    fromCity: "Aurangabad",
    toCity: "Gaya",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "sasaram-to-gaya",
    fromCity: "Sasaram",
    toCity: "Gaya",
    distance: 130,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "buxar-to-gaya",
    fromCity: "Buxar",
    toCity: "Gaya",
    distance: 180,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "varanasi-to-gaya",
    fromCity: "Varanasi",
    toCity: "Gaya",
    distance: 240,
    duration: "5 - 6 hrs",
  },
  {
    slug: "prayagraj-to-gaya",
    fromCity: "Prayagraj",
    toCity: "Gaya",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ranchi-to-gaya",
    fromCity: "Ranchi",
    toCity: "Gaya",
    distance: 315,
    duration: "6 - 7 hrs",
  },
  {
    slug: "hazaribagh-to-gaya",
    fromCity: "Hazaribagh",
    toCity: "Gaya",
    distance: 220,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "dhanbad-to-gaya",
    fromCity: "Dhanbad",
    toCity: "Gaya",
    distance: 190,
    duration: "4 - 5 hrs",
  },
  {
    slug: "jamshedpur-to-gaya",
    fromCity: "Jamshedpur",
    toCity: "Gaya",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "bokaro-to-gaya",
    fromCity: "Bokaro",
    toCity: "Gaya",
    distance: 230,
    duration: "5 - 6 hrs",
  },
  {
    slug: "deoghar-to-gaya",
    fromCity: "Deoghar",
    toCity: "Gaya",
    distance: 240,
    duration: "5 - 6 hrs",
  },
  {
    slug: "dumka-to-gaya",
    fromCity: "Dumka",
    toCity: "Gaya",
    distance: 300,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "giridih-to-gaya",
    fromCity: "Giridih",
    toCity: "Gaya",
    distance: 180,
    duration: "4 - 5 hrs",
  },
  {
    slug: "jamtara-to-gaya",
    fromCity: "Jamtara",
    toCity: "Gaya",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "muzaffarpur-to-gaya",
    fromCity: "Muzaffarpur",
    toCity: "Gaya",
    distance: 220,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "darbhanga-to-gaya",
    fromCity: "Darbhanga",
    toCity: "Gaya",
    distance: 260,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "bhagalpur-to-gaya",
    fromCity: "Bhagalpur",
    toCity: "Gaya",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "munger-to-gaya",
    fromCity: "Munger",
    toCity: "Gaya",
    distance: 180,
    duration: "4 - 5 hrs",
  },
  {
    slug: "begusarai-to-gaya",
    fromCity: "Begusarai",
    toCity: "Gaya",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },
  {
    slug: "samastipur-to-gaya",
    fromCity: "Samastipur",
    toCity: "Gaya",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "hajipur-to-gaya",
    fromCity: "Hajipur",
    toCity: "Gaya",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "chapra-to-gaya",
    fromCity: "Chapra",
    toCity: "Gaya",
    distance: 180,
    duration: "4 - 5 hrs",
  },
  {
    slug: "siwan-to-gaya",
    fromCity: "Siwan",
    toCity: "Gaya",
    distance: 230,
    duration: "5 - 6 hrs",
  },
  {
    slug: "bettiah-to-gaya",
    fromCity: "Bettiah",
    toCity: "Gaya",
    distance: 320,
    duration: "7 - 8 hrs",
  },
  {
    slug: "motihari-to-gaya",
    fromCity: "Motihari",
    toCity: "Gaya",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "purnia-to-gaya",
    fromCity: "Purnia",
    toCity: "Gaya",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "katihar-to-gaya",
    fromCity: "Katihar",
    toCity: "Gaya",
    distance: 380,
    duration: "8 - 9 hrs",
  },
  {
    slug: "kishanganj-to-gaya",
    fromCity: "Kishanganj",
    toCity: "Gaya",
    distance: 420,
    duration: "9 - 10 hrs",
  },
  {
    slug: "saharsa-to-gaya",
    fromCity: "Saharsa",
    toCity: "Gaya",
    distance: 300,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "madhepura-to-gaya",
    fromCity: "Madhepura",
    toCity: "Gaya",
    distance: 320,
    duration: "7 - 8 hrs",
  },
  {
    slug: "supaul-to-gaya",
    fromCity: "Supaul",
    toCity: "Gaya",
    distance: 340,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "araria-to-gaya",
    fromCity: "Araria",
    toCity: "Gaya",
    distance: 370,
    duration: "8 - 9 hrs",
  },
  {
    slug: "jamui-to-gaya",
    fromCity: "Jamui",
    toCity: "Gaya",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "banka-to-gaya",
    fromCity: "Banka",
    toCity: "Gaya",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },
  {
    slug: "lucknow-to-gaya",
    fromCity: "Lucknow",
    toCity: "Gaya",
    distance: 420,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ayodhya-to-gaya",
    fromCity: "Ayodhya",
    toCity: "Gaya",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "gorakhpur-to-gaya",
    fromCity: "Gorakhpur",
    toCity: "Gaya",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "kanpur-to-gaya",
    fromCity: "Kanpur",
    toCity: "Gaya",
    distance: 450,
    duration: "9 - 10 hrs",
  },
  {
    slug: "delhi-to-gaya",
    fromCity: "Delhi",
    toCity: "Gaya",
    distance: 1000,
    duration: "16 - 18 hrs",
  },
  {
    slug: "kolkata-to-gaya",
    fromCity: "Kolkata",
    toCity: "Gaya",
    distance: 460,
    duration: "9 - 10 hrs",
  },
  {
    slug: "bhubaneswar-to-gaya",
    fromCity: "Bhubaneswar",
    toCity: "Gaya",
    distance: 650,
    duration: "12 - 14 hrs",
  },
  {
    slug: "raipur-to-gaya",
    fromCity: "Raipur",
    toCity: "Gaya",
    distance: 600,
    duration: "11 - 12 hrs",
  },
  {
    slug: "nagpur-to-gaya",
    fromCity: "Nagpur",
    toCity: "Gaya",
    distance: 800,
    duration: "14 - 16 hrs",
  },
  {
    slug: "guwahati-to-gaya",
    fromCity: "Guwahati",
    toCity: "Gaya",
    distance: 850,
    duration: "16 - 18 hrs",
  },
  // --- Vindhyachal Popular Routes ---
  // --- Routes FROM Vindhyachal ---

  {
    slug: "vindhyachal-to-mirzapur",
    fromCity: "Vindhyachal",
    toCity: "Mirzapur",
    distance: 10,
    duration: "20 - 30 min",
  },

  {
    slug: "vindhyachal-to-varanasi",
    fromCity: "Vindhyachal",
    toCity: "Varanasi",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "vindhyachal-to-prayagraj",
    fromCity: "Vindhyachal",
    toCity: "Prayagraj",
    distance: 85,
    duration: "2 hrs",
  },

  {
    slug: "vindhyachal-to-chunar",
    fromCity: "Vindhyachal",
    toCity: "Chunar",
    distance: 30,
    duration: "45 min - 1 hr",
  },

  {
    slug: "vindhyachal-to-robertsganj",
    fromCity: "Vindhyachal",
    toCity: "Robertsganj",
    distance: 80,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "vindhyachal-to-chopan",
    fromCity: "Vindhyachal",
    toCity: "Chopan",
    distance: 100,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "vindhyachal-to-obra",
    fromCity: "Vindhyachal",
    toCity: "Obra",
    distance: 110,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "vindhyachal-to-singrauli",
    fromCity: "Vindhyachal",
    toCity: "Singrauli",
    distance: 150,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "vindhyachal-to-jaunpur",
    fromCity: "Vindhyachal",
    toCity: "Jaunpur",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "vindhyachal-to-ghazipur",
    fromCity: "Vindhyachal",
    toCity: "Ghazipur",
    distance: 120,
    duration: "2.5 - 3 hrs",
  },

  {
    slug: "vindhyachal-to-chandauli",
    fromCity: "Vindhyachal",
    toCity: "Chandauli",
    distance: 50,
    duration: "1 - 1.5 hrs",
  },

  {
    slug: "vindhyachal-to-bhadohi",
    fromCity: "Vindhyachal",
    toCity: "Bhadohi",
    distance: 60,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "vindhyachal-to-lucknow",
    fromCity: "Vindhyachal",
    toCity: "Lucknow",
    distance: 250,
    duration: "5 - 6 hrs",
  },

  {
    slug: "vindhyachal-to-kanpur",
    fromCity: "Vindhyachal",
    toCity: "Kanpur",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "vindhyachal-to-ayodhya",
    fromCity: "Vindhyachal",
    toCity: "Ayodhya",
    distance: 230,
    duration: "5 - 6 hrs",
  },

  {
    slug: "vindhyachal-to-gorakhpur",
    fromCity: "Vindhyachal",
    toCity: "Gorakhpur",
    distance: 250,
    duration: "5.5 - 6.5 hrs",
  },

  {
    slug: "vindhyachal-to-delhi",
    fromCity: "Vindhyachal",
    toCity: "Delhi",
    distance: 750,
    duration: "12 - 14 hrs",
  },

  {
    slug: "vindhyachal-to-noida",
    fromCity: "Vindhyachal",
    toCity: "Noida",
    distance: 760,
    duration: "13 - 15 hrs",
  },

  {
    slug: "vindhyachal-to-agra",
    fromCity: "Vindhyachal",
    toCity: "Agra",
    distance: 550,
    duration: "10 - 11 hrs",
  },

  {
    slug: "vindhyachal-to-mathura",
    fromCity: "Vindhyachal",
    toCity: "Mathura",
    distance: 530,
    duration: "10 - 11 hrs",
  },

  {
    slug: "vindhyachal-to-vrindavan",
    fromCity: "Vindhyachal",
    toCity: "Vrindavan",
    distance: 535,
    duration: "10 - 11 hrs",
  },

  {
    slug: "vindhyachal-to-chitrakoot",
    fromCity: "Vindhyachal",
    toCity: "Chitrakoot",
    distance: 180,
    duration: "4 - 5 hrs",
  },

  {
    slug: "vindhyachal-to-banda",
    fromCity: "Vindhyachal",
    toCity: "Banda",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "vindhyachal-to-satna",
    fromCity: "Vindhyachal",
    toCity: "Satna",
    distance: 200,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "vindhyachal-to-rewa",
    fromCity: "Vindhyachal",
    toCity: "Rewa",
    distance: 230,
    duration: "5 - 6 hrs",
  },

  {
    slug: "vindhyachal-to-jabalpur",
    fromCity: "Vindhyachal",
    toCity: "Jabalpur",
    distance: 320,
    duration: "6.5 - 7.5 hrs",
  },

  {
    slug: "vindhyachal-to-sasaram",
    fromCity: "Vindhyachal",
    toCity: "Sasaram",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },

  {
    slug: "vindhyachal-to-buxar",
    fromCity: "Vindhyachal",
    toCity: "Buxar",
    distance: 150,
    duration: "3 - 4 hrs",
  },

  {
    slug: "vindhyachal-to-patna",
    fromCity: "Vindhyachal",
    toCity: "Patna",
    distance: 220,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "vindhyachal-to-gaya",
    fromCity: "Vindhyachal",
    toCity: "Gaya",
    distance: 240,
    duration: "5 - 6 hrs",
  },

  {
    slug: "vindhyachal-to-bodh-gaya",
    fromCity: "Vindhyachal",
    toCity: "Bodh Gaya",
    distance: 255,
    duration: "5.5 - 6.5 hrs",
  },

  {
    slug: "vindhyachal-to-ranchi",
    fromCity: "Vindhyachal",
    toCity: "Ranchi",
    distance: 380,
    duration: "8 - 9 hrs",
  },

  {
    slug: "vindhyachal-to-dhanbad",
    fromCity: "Vindhyachal",
    toCity: "Dhanbad",
    distance: 260,
    duration: "5.5 - 6.5 hrs",
  },

  {
    slug: "vindhyachal-to-kolkata",
    fromCity: "Vindhyachal",
    toCity: "Kolkata",
    distance: 650,
    duration: "12 - 14 hrs",
  },

  {
    slug: "vindhyachal-to-nalanda",
    fromCity: "Vindhyachal",
    toCity: "Nalanda",
    distance: 210,
    duration: "4.5 - 5.5 hrs",
  },

  {
    slug: "vindhyachal-to-rajgir",
    fromCity: "Vindhyachal",
    toCity: "Rajgir",
    distance: 230,
    duration: "5 - 6 hrs",
  },

  {
    slug: "vindhyachal-to-deoghar",
    fromCity: "Vindhyachal",
    toCity: "Deoghar",
    distance: 350,
    duration: "7.5 - 8.5 hrs",
  },

  {
    slug: "vindhyachal-to-sarnath",
    fromCity: "Vindhyachal",
    toCity: "Sarnath",
    distance: 75,
    duration: "1.5 - 2 hrs",
  },

  {
    slug: "vindhyachal-to-sultanpur",
    fromCity: "Vindhyachal",
    toCity: "Sultanpur",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "vindhyachal-to-amethi",
    fromCity: "Vindhyachal",
    toCity: "Amethi",
    distance: 140,
    duration: "3 - 4 hrs",
  },

  {
    slug: "vindhyachal-to-rae-bareli",
    fromCity: "Vindhyachal",
    toCity: "Rae Bareli",
    distance: 160,
    duration: "3.5 - 4.5 hrs",
  },

  {
    slug: "vindhyachal-to-fatehpur",
    fromCity: "Vindhyachal",
    toCity: "Fatehpur",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },

  {
    slug: "vindhyachal-to-jhansi",
    fromCity: "Vindhyachal",
    toCity: "Jhansi",
    distance: 320,
    duration: "6.5 - 7.5 hrs",
  },

  {
    slug: "vindhyachal-to-khajuraho",
    fromCity: "Vindhyachal",
    toCity: "Khajuraho",
    distance: 280,
    duration: "6 - 7 hrs",
  },

  {
    slug: "vindhyachal-to-orchha",
    fromCity: "Vindhyachal",
    toCity: "Orchha",
    distance: 330,
    duration: "7 - 8 hrs",
  },

  {
    slug: "vindhyachal-to-gwalior",
    fromCity: "Vindhyachal",
    toCity: "Gwalior",
    distance: 420,
    duration: "8.5 - 9.5 hrs",
  },

  {
    slug: "vindhyachal-to-bhopal",
    fromCity: "Vindhyachal",
    toCity: "Bhopal",
    distance: 580,
    duration: "11 - 12 hrs",
  },

  {
    slug: "vindhyachal-to-indore",
    fromCity: "Vindhyachal",
    toCity: "Indore",
    distance: 730,
    duration: "13 - 14 hrs",
  },

  {
    slug: "vindhyachal-to-jaipur",
    fromCity: "Vindhyachal",
    toCity: "Jaipur",
    distance: 680,
    duration: "12 - 13 hrs",
  },

  {
    slug: "vindhyachal-to-haridwar",
    fromCity: "Vindhyachal",
    toCity: "Haridwar",
    distance: 780,
    duration: "14 - 15 hrs",
  },

  // --- Missing Routes TO Ayodhya ---
  {
    slug: "gorakhpur-to-ayodhya",
    fromCity: "Gorakhpur",
    toCity: "Ayodhya",
    distance: 135,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "kanpur-to-ayodhya",
    fromCity: "Kanpur",
    toCity: "Ayodhya",
    distance: 200,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "patna-to-ayodhya",
    fromCity: "Patna",
    toCity: "Ayodhya",
    distance: 280,
    duration: "6 - 7 hrs",
  },
  {
    slug: "agra-to-ayodhya",
    fromCity: "Agra",
    toCity: "Ayodhya",
    distance: 400,
    duration: "7 - 8 hrs",
  },
  {
    slug: "mathura-to-ayodhya",
    fromCity: "Mathura",
    toCity: "Ayodhya",
    distance: 380,
    duration: "7 - 8 hrs",
  },
  {
    slug: "basti-to-ayodhya",
    fromCity: "Basti",
    toCity: "Ayodhya",
    distance: 100,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "gonda-to-ayodhya",
    fromCity: "Gonda",
    toCity: "Ayodhya",
    distance: 60,
    duration: "1.5 hrs",
  },
  {
    slug: "sultanpur-to-ayodhya",
    fromCity: "Sultanpur",
    toCity: "Ayodhya",
    distance: 85,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "faizabad-to-ayodhya",
    fromCity: "Faizabad",
    toCity: "Ayodhya",
    distance: 6,
    duration: "15 - 20 min",
  },
  {
    slug: "jaunpur-to-ayodhya",
    fromCity: "Jaunpur",
    toCity: "Ayodhya",
    distance: 170,
    duration: "4 - 5 hrs",
  },
  {
    slug: "pratapgarh-to-ayodhya",
    fromCity: "Pratapgarh",
    toCity: "Ayodhya",
    distance: 100,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "rae-bareli-to-ayodhya",
    fromCity: "Rae Bareli",
    toCity: "Ayodhya",
    distance: 130,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "ambedkar-nagar-to-ayodhya",
    fromCity: "Ambedkar Nagar",
    toCity: "Ayodhya",
    distance: 70,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "azamgarh-to-ayodhya",
    fromCity: "Azamgarh",
    toCity: "Ayodhya",
    distance: 140,
    duration: "3 - 4 hrs",
  },
  {
    slug: "deoria-to-ayodhya",
    fromCity: "Deoria",
    toCity: "Ayodhya",
    distance: 220,
    duration: "5 - 6 hrs",
  },
  {
    slug: "maharajganj-to-ayodhya",
    fromCity: "Maharajganj",
    toCity: "Ayodhya",
    distance: 240,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "bareilly-to-ayodhya",
    fromCity: "Bareilly",
    toCity: "Ayodhya",
    distance: 280,
    duration: "5.5 - 6.5 hrs",
  },
  {
    slug: "moradabad-to-ayodhya",
    fromCity: "Moradabad",
    toCity: "Ayodhya",
    distance: 330,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "aligarh-to-ayodhya",
    fromCity: "Aligarh",
    toCity: "Ayodhya",
    distance: 400,
    duration: "8 - 9 hrs",
  },
  {
    slug: "ghaziabad-to-ayodhya",
    fromCity: "Ghaziabad",
    toCity: "Ayodhya",
    distance: 550,
    duration: "9 - 10 hrs",
  },
  {
    slug: "noida-to-ayodhya",
    fromCity: "Noida",
    toCity: "Ayodhya",
    distance: 570,
    duration: "10 - 11 hrs",
  },
  {
    slug: "greater-noida-to-ayodhya",
    fromCity: "Greater Noida",
    toCity: "Ayodhya",
    distance: 580,
    duration: "10 - 11 hrs",
  },
  {
    slug: "meerut-to-ayodhya",
    fromCity: "Meerut",
    toCity: "Ayodhya",
    distance: 600,
    duration: "11 - 12 hrs",
  },
  {
    slug: "gaya-to-ayodhya",
    fromCity: "Gaya",
    toCity: "Ayodhya",
    distance: 330,
    duration: "7 - 8 hrs",
  },
  {
    slug: "bodh-gaya-to-ayodhya",
    fromCity: "Bodh Gaya",
    toCity: "Ayodhya",
    distance: 360,
    duration: "8 - 9 hrs",
  },
  {
    slug: "muzaffarpur-to-ayodhya",
    fromCity: "Muzaffarpur",
    toCity: "Ayodhya",
    distance: 320,
    duration: "7 - 8 hrs",
  },
  {
    slug: "darbhanga-to-ayodhya",
    fromCity: "Darbhanga",
    toCity: "Ayodhya",
    distance: 360,
    duration: "8 - 9 hrs",
  },
  {
    slug: "vrindavan-to-ayodhya",
    fromCity: "Vrindavan",
    toCity: "Ayodhya",
    distance: 390,
    duration: "7 - 8 hrs",
  },
  {
    slug: "jaipur-to-ayodhya",
    fromCity: "Jaipur",
    toCity: "Ayodhya",
    distance: 750,
    duration: "13 - 14 hrs",
  },
  {
    slug: "haridwar-to-ayodhya",
    fromCity: "Haridwar",
    toCity: "Ayodhya",
    distance: 680,
    duration: "12 - 13 hrs",
  },
  {
    slug: "rishikesh-to-ayodhya",
    fromCity: "Rishikesh",
    toCity: "Ayodhya",
    distance: 700,
    duration: "13 - 14 hrs",
  },
  {
    slug: "dehradun-to-ayodhya",
    fromCity: "Dehradun",
    toCity: "Ayodhya",
    distance: 720,
    duration: "13 - 14 hrs",
  },
  {
    slug: "jhansi-to-ayodhya",
    fromCity: "Jhansi",
    toCity: "Ayodhya",
    distance: 420,
    duration: "8 - 9 hrs",
  },
  {
    slug: "chitrakoot-to-ayodhya",
    fromCity: "Chitrakoot",
    toCity: "Ayodhya",
    distance: 200,
    duration: "4.5 - 5 hrs",
  },
  {
    slug: "shravasti-to-ayodhya",
    fromCity: "Shravasti",
    toCity: "Ayodhya",
    distance: 90,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "kolkata-to-ayodhya",
    fromCity: "Kolkata",
    toCity: "Ayodhya",
    distance: 650,
    duration: "12 - 14 hrs",
  },
  {
    slug: "ranchi-to-ayodhya",
    fromCity: "Ranchi",
    toCity: "Ayodhya",
    distance: 500,
    duration: "10 - 11 hrs",
  },
  {
    slug: "dhanbad-to-ayodhya",
    fromCity: "Dhanbad",
    toCity: "Ayodhya",
    distance: 420,
    duration: "9 - 10 hrs",
  },
  {
    slug: "jamshedpur-to-ayodhya",
    fromCity: "Jamshedpur",
    toCity: "Ayodhya",
    distance: 550,
    duration: "11 - 12 hrs",
  },
  {
    slug: "bhopal-to-ayodhya",
    fromCity: "Bhopal",
    toCity: "Ayodhya",
    distance: 650,
    duration: "12 - 13 hrs",
  },
  {
    slug: "indore-to-ayodhya",
    fromCity: "Indore",
    toCity: "Ayodhya",
    distance: 800,
    duration: "14 - 16 hrs",
  },
  {
    slug: "ujjain-to-ayodhya",
    fromCity: "Ujjain",
    toCity: "Ayodhya",
    distance: 750,
    duration: "14 - 15 hrs",
  },
  // --- Agra Popular Routes ---
  {
    slug: "agra-to-delhi",
    fromCity: "Agra",
    toCity: "Delhi",
    distance: 230,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "agra-to-jaipur",
    fromCity: "Agra",
    toCity: "Jaipur",
    distance: 240,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "agra-to-gwalior",
    fromCity: "Agra",
    toCity: "Gwalior",
    distance: 120,
    duration: "2 - 2.5 hrs",
  },
  {
    slug: "agra-to-mathura",
    fromCity: "Agra",
    toCity: "Mathura",
    distance: 60,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "agra-to-vrindavan",
    fromCity: "Agra",
    toCity: "Vrindavan",
    distance: 65,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "agra-to-bharatpur",
    fromCity: "Agra",
    toCity: "Bharatpur",
    distance: 55,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "agra-to-fatehpur-sikri",
    fromCity: "Agra",
    toCity: "Fatehpur Sikri",
    distance: 35,
    duration: "45 min - 1 hr",
  },
  {
    slug: "agra-to-dholpur",
    fromCity: "Agra",
    toCity: "Dholpur",
    distance: 60,
    duration: "1 - 1.5 hrs",
  },
  {
    slug: "agra-to-morena",
    fromCity: "Agra",
    toCity: "Morena",
    distance: 80,
    duration: "1.5 - 2 hrs",
  },
  {
    slug: "agra-to-jhansi",
    fromCity: "Agra",
    toCity: "Jhansi",
    distance: 200,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "agra-to-datia",
    fromCity: "Agra",
    toCity: "Datia",
    distance: 150,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "agra-to-shivpuri",
    fromCity: "Agra",
    toCity: "Shivpuri",
    distance: 180,
    duration: "3 - 4 hrs",
  },
  {
    slug: "agra-to-guna",
    fromCity: "Agra",
    toCity: "Guna",
    distance: 220,
    duration: "4 - 4.5 hrs",
  },
  {
    slug: "agra-to-bhopal",
    fromCity: "Agra",
    toCity: "Bhopal",
    distance: 450,
    duration: "7 - 8 hrs",
  },
  {
    slug: "agra-to-indore",
    fromCity: "Agra",
    toCity: "Indore",
    distance: 550,
    duration: "9 - 10 hrs",
  },
  {
    slug: "agra-to-udaipur",
    fromCity: "Agra",
    toCity: "Udaipur",
    distance: 600,
    duration: "10 - 11 hrs",
  },
  {
    slug: "agra-to-ajmer",
    fromCity: "Agra",
    toCity: "Ajmer",
    distance: 380,
    duration: "6 - 7 hrs",
  },
  {
    slug: "agra-to-pushkar",
    fromCity: "Agra",
    toCity: "Pushkar",
    distance: 390,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "agra-to-alwar",
    fromCity: "Agra",
    toCity: "Alwar",
    distance: 160,
    duration: "2.5 - 3.5 hrs",
  },
  {
    slug: "agra-to-karauli",
    fromCity: "Agra",
    toCity: "Karauli",
    distance: 140,
    duration: "2.5 - 3 hrs",
  },
  {
    slug: "agra-to-sawai-madhopur",
    fromCity: "Agra",
    toCity: "Sawai Madhopur",
    distance: 200,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "agra-to-tonk",
    fromCity: "Agra",
    toCity: "Tonk",
    distance: 300,
    duration: "5 - 6 hrs",
  },
  {
    slug: "agra-to-bundi",
    fromCity: "Agra",
    toCity: "Bundi",
    distance: 350,
    duration: "6 - 7 hrs",
  },
  {
    slug: "agra-to-kota",
    fromCity: "Agra",
    toCity: "Kota",
    distance: 400,
    duration: "6.5 - 7.5 hrs",
  },
  {
    slug: "agra-to-chittorgarh",
    fromCity: "Agra",
    toCity: "Chittorgarh",
    distance: 480,
    duration: "8 - 9 hrs",
  },
  {
    slug: "agra-to-bhilwara",
    fromCity: "Agra",
    toCity: "Bhilwara",
    distance: 450,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "agra-to-neemrana",
    fromCity: "Agra",
    toCity: "Neemrana",
    distance: 140,
    duration: "2 - 3 hrs",
  },
  {
    slug: "agra-to-behror",
    fromCity: "Agra",
    toCity: "Behror",
    distance: 180,
    duration: "3 - 3.5 hrs",
  },
  {
    slug: "agra-to-khetri",
    fromCity: "Agra",
    toCity: "Khetri",
    distance: 200,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "agra-to-jhunjhunu",
    fromCity: "Agra",
    toCity: "Jhunjhunu",
    distance: 250,
    duration: "4 - 5 hrs",
  },
  {
    slug: "agra-to-sikar",
    fromCity: "Agra",
    toCity: "Sikar",
    distance: 300,
    duration: "5 - 6 hrs",
  },
  {
    slug: "agra-to-churu",
    fromCity: "Agra",
    toCity: "Churu",
    distance: 350,
    duration: "6 - 7 hrs",
  },
  {
    slug: "agra-to-bikaner",
    fromCity: "Agra",
    toCity: "Bikaner",
    distance: 550,
    duration: "9 - 10 hrs",
  },
  {
    slug: "agra-to-jodhpur",
    fromCity: "Agra",
    toCity: "Jodhpur",
    distance: 580,
    duration: "9.5 - 10.5 hrs",
  },
  {
    slug: "agra-to-jaisalmer",
    fromCity: "Agra",
    toCity: "Jaisalmer",
    distance: 750,
    duration: "12 - 13 hrs",
  },
  {
    slug: "agra-to-mount-abu",
    fromCity: "Agra",
    toCity: "Mount Abu",
    distance: 650,
    duration: "11 - 12 hrs",
  },
  {
    slug: "agra-to-lucknow",
    fromCity: "Agra",
    toCity: "Lucknow",
    distance: 400,
    duration: "7 - 8 hrs",
  },
  {
    slug: "agra-to-kanpur",
    fromCity: "Agra",
    toCity: "Kanpur",
    distance: 300,
    duration: "5 - 6 hrs",
  },
  {
    slug: "agra-to-prayagraj",
    fromCity: "Agra",
    toCity: "Prayagraj",
    distance: 450,
    duration: "8 - 9 hrs",
  },
  {
    slug: "agra-to-varanasi",
    fromCity: "Agra",
    toCity: "Varanasi",
    distance: 600,
    duration: "10 - 11 hrs",
  },
  {
    slug: "agra-to-ayodhya",
    fromCity: "Agra",
    toCity: "Ayodhya",
    distance: 450,
    duration: "8 - 9 hrs",
  },
  {
    slug: "agra-to-noida",
    fromCity: "Agra",
    toCity: "Noida",
    distance: 210,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "agra-to-gurugram",
    fromCity: "Agra",
    toCity: "Gurugram",
    distance: 220,
    duration: "3.5 - 4 hrs",
  },
  {
    slug: "agra-to-faridabad",
    fromCity: "Agra",
    toCity: "Faridabad",
    distance: 200,
    duration: "3 - 4 hrs",
  },
  {
    slug: "agra-to-chandigarh",
    fromCity: "Agra",
    toCity: "Chandigarh",
    distance: 450,
    duration: "7 - 8 hrs",
  },
  {
    slug: "agra-to-dehradun",
    fromCity: "Agra",
    toCity: "Dehradun",
    distance: 450,
    duration: "8 - 9 hrs",
  },
  {
    slug: "agra-to-haridwar",
    fromCity: "Agra",
    toCity: "Haridwar",
    distance: 420,
    duration: "7 - 8 hrs",
  },
  {
    slug: "agra-to-rishikesh",
    fromCity: "Agra",
    toCity: "Rishikesh",
    distance: 430,
    duration: "7.5 - 8.5 hrs",
  },
  {
    slug: "agra-to-bareilly",
    fromCity: "Agra",
    toCity: "Bareilly",
    distance: 350,
    duration: "6 - 7 hrs",
  },
  {
    slug: "agra-to-moradabad",
    fromCity: "Agra",
    toCity: "Moradabad",
    distance: 400,
    duration: "7 - 8 hrs",
  },
];
