export const featuredBoats = [
  {
    id: 1,
    title: "Luxury Houseboat Cruise",
    location: "Alleppey, Kerala",
    image: "/boat3.jpg",
    rating: 4.9,
    price: 6999,
  },
  {
    id: 2,
    title: "Sunset Ganga Boat Ride",
    location: "Varanasi",
    image: "/boat5.jpg",
    rating: 4.8,
    price: 799,
  },
  {
    id: 3,
    title: "Dal Lake Shikara Ride",
    location: "Srinagar",
    image: "/boat4.jpg",
    rating: 5,
    price: 1499,
  },
  {
    id: 4,
    title: "Goa Sunset Cruise",
    location: "Goa",
    image: "/boat1.jpg",
    rating: 4.7,
    price: 1999,
  },
  {
    id: 5,
    title: "Andaman Glass Bottom Boat",
    location: "Havelock Island",
    image: "/boat2.jpg",
    rating: 4.9,
    price: 2499,
  },
];