export const featuredHotels = [
  {
    id: 1,
    name: "The Grand Palace",
    slug: "the-grand-palace",
    city: "delhi",
    location: "New Delhi",
    image: "/GrandHotelNewDelhi.jpg",
    rating: 4.8,
    price: 4999,
  },
  {
    id: 2,
    name: "Royal Heritage",
    slug: "royal-heritage",
    city: "jaipur",
    location: "Jaipur",
    image: "/RoyalHeritageJaipur.jpg",
    rating: 4.7,
    price: 3799,
  },
  {
    id: 3,
    name: "Sea Breeze Resort",
    slug: "sea-breeze-resort",
    city: "goa",
    location: "Goa",
    image: "/SeaBreezeGoa.jpg",
    rating: 4.9,
    price: 5999,
  },
];
