export const popularPackages = [
  {
    id: 1,
    title: "Goa Beach & Nightlife",
    image: "/packages/goa_package.jpg",
    price: "₹8,999",
    packageCount: "45+ Packages",
    description: "Golden beaches, vibrant nightlife & water sports adventures.",
    slug: "goa",
    duration: "4 Days",
    groupSize: "2-6 People",
    type: "Family & Couples",
    location: "Goa, India",
    tags: ["Beach", "Nightlife", "Water Sports"],
    highlights: ["Baga Beach", "Cruise", "Water Sports"],
  },
  {
    id: 2,
    title: "Kashmir Paradise Tour",
    image: "/packages/kashmir_package.jpg",
    price: "₹14,999",
    packageCount: "32+ Packages",
    description: "Snow-covered mountains, scenic valleys & houseboat stays.",
    slug: "kashmir",
    duration: "5 Days",
    groupSize: "2-8 People",
    type: "Honeymoon & Family",
    location: "Kashmir, India",
    tags: ["Mountains", "Snow", "Houseboat"],
    highlights: ["Dal Lake", "Gulmarg", "Pahalgam"],
  },
  {
    id: 3,
    title: "Kerala Backwaters Escape",
    image: "/packages/Kerala_boats.jpg",
    price: "₹11,999",
    packageCount: "40+ Packages",
    description: "Serene backwaters, tea gardens & pristine beaches.",
    slug: "kerala",
    duration: "4 Days",
    groupSize: "2-6 People",
    type: "Couples & Solo",
    location: "Kerala, India",
    tags: ["Backwaters", "Tea Gardens", "Beaches"],
    highlights: ["Alleppey", "Munnar", "Kovalam"],
  },
  {
    id: 4,
    title: "Rajasthan Royal Heritage",
    image: "/packages/package_rajasthan.jpg",
    price: "₹10,999",
    packageCount: "38+ Packages",
    description: "Royal palaces, majestic forts & desert adventures.",
    slug: "rajasthan",
    duration: "5 Days",
    groupSize: "2-10 People",
    type: "Cultural & Heritage",
    location: "Rajasthan, India",
    tags: ["Palaces", "Desert", "Heritage"],
    highlights: ["Jaipur", "Jaisalmer", "Udaipur"],
  },
  {
    id: 5,
    title: "Himachal Mountain Retreat",
    image: "/packages/Himachal_package.jpg",
    price: "₹12,499",
    packageCount: "36+ Packages",
    description: "Shimla, Manali & scenic mountain escapes.",
    slug: "himachal",
    duration: "4 Days",
    groupSize: "2-8 People",
    type: "Family & Adventure",
    location: "Himachal, India",
    tags: ["Mountains", "Adventure", "Snow"],
    highlights: ["Shimla", "Manali", "Rohtang Pass"],
  },

  {
    id: 7,
    title: "Uttarakhand Spiritual Journey",
    image: "/packages/Uttrakhand_package.jpg",
    price: "₹9,999",
    packageCount: "30+ Packages",
    description: "Rishikesh, Mussoorie & spiritual Himalayan experiences.",
    slug: "uttarakhand",
    duration: "4 Days",
    groupSize: "2-8 People",
    type: "Spiritual & Family",
    location: "Uttarakhand, India",
    tags: ["Spiritual", "Mountains", "Adventure"],
    highlights: ["Rishikesh", "Mussoorie", "Haridwar"],
  },
  {
    id: 8,
    title: "North East Discovery Tour",
    image: "/packages/northEast_package.jpg",
    price: "₹17,999",
    packageCount: "22+ Packages",
    description: "Meghalaya, Sikkim & Arunachal hidden gems.",
    slug: "north-east",
    duration: "6 Days",
    groupSize: "2-8 People",
    type: "Adventure & Culture",
    location: "North East, India",
    tags: ["Hill Stations", "Culture", "Waterfalls"],
    highlights: ["Shillong", "Gangtok", "Tawang"],
  },
  {
    id: 9,
    title: "Tamil Nadu Temple Trail",
    image: "/packages/tamilNaidu_package.jpg",
    price: "₹12,999",
    packageCount: "25+ Packages",
    description: "Ancient temples, Dravidian architecture & cultural heritage.",
    slug: "tamil-nadu",
    duration: "5 Days",
    groupSize: "2-10 People",
    type: "Cultural & Spiritual",
    location: "Tamil Nadu, India",
    tags: ["Temples", "Heritage", "Culture"],
    highlights: ["Meenakshi Temple", "Brihadeeswarar", "Rameswaram"],
  },
  {
    id: 10,
    title: "Sikkim Himalayan Wonder",
    image: "/packages/Sikkim_package.jpg",
    price: "₹15,999",
    packageCount: "18+ Packages",
    description: "Buddhist monasteries, snow peaks & pristine landscapes.",
    slug: "sikkim",
    duration: "6 Days",
    groupSize: "2-8 People",
    type: "Adventure & Spiritual",
    location: "Sikkim, India",
    tags: ["Mountains", "Monasteries", "Nature"],
    highlights: ["Gangtok", "Nathu La", "Tsomgo Lake"],
  },
  {
    id: 11,
    title: "Odisha Cultural Odyssey",
    image: "/packages/odisha.jpg",
    price: "₹10,499",
    packageCount: "20+ Packages",
    description: "Ancient temples, tribal culture & pristine beaches.",
    slug: "odisha",
    duration: "4 Days",
    groupSize: "2-8 People",
    type: "Cultural & Heritage",
    location: "Odisha, India",
    tags: ["Temples", "Culture", "Beaches"],
    highlights: ["Konark", "Puri", "Bhubaneswar"],
  },
  {
    id: 12,
    title: "Gujarat Vibrant Tour",
    image: "/packages/gujarat.jpg",
    price: "₹11,499",
    packageCount: "28+ Packages",
    description: "White desert, Asiatic lions & rich cultural heritage.",
    slug: "gujarat",
    duration: "5 Days",
    groupSize: "2-10 People",
    type: "Cultural & Wildlife",
    location: "Gujarat, India",
    tags: ["Desert", "Wildlife", "Heritage"],
    highlights: ["Rann of Kutch", "Gir National Park", "Somnath"],
  },
  {
    id: 13,
    title: "Madhya Pradesh Wildlife Safari",
    image: "/packages/madhyapradesh.jpg",
    price: "₹13,499",
    packageCount: "20+ Packages",
    description: "Tiger reserves, ancient caves & historical wonders.",
    slug: "madhya-pradesh",
    duration: "5 Days",
    groupSize: "2-8 People",
    type: "Wildlife & Heritage",
    location: "Madhya Pradesh, India",
    tags: ["Wildlife", "Tigers", "Heritage"],
    highlights: ["Bandhavgarh", "Kanha", "Sanchi"],
  },
  {
    id: 14,
    title: "Punjab Golden Temple Tour",
    image: "/packages/punjab.jpg",
    price: "₹8,499",
    packageCount: "25+ Packages",
    description: "Golden Temple, vibrant culture & delicious cuisine.",
    slug: "punjab",
    duration: "3 Days",
    groupSize: "2-8 People",
    type: "Spiritual & Cultural",
    location: "Punjab, India",
    tags: ["Spiritual", "Culture", "Heritage"],
    highlights: ["Golden Temple", "Jallianwala Bagh", "Wagah Border"],
  },
  {
    id: 15,
    title: "Ladakh Adventure Expedition",
    image: "/packages/ladakh.jpg",
    price: "₹19,999",
    packageCount: "15+ Packages",
    description:
      "High-altitude deserts, breathtaking landscapes & Buddhist culture.",
    slug: "ladakh",
    duration: "7 Days",
    groupSize: "2-6 People",
    type: "Adventure & Spiritual",
    location: "Ladakh, India",
    tags: ["Mountains", "Adventure", "Monasteries"],
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La"],
  },
];
