export const popularRoutes = [
  {
    id: 1,
    from: "Delhi",
    to: "Agra",
    distance: "233 km",
    duration: "3.5 hrs",
    image: "/popular_cab_route7.jpg",
    popular: true,
  },
  {
    id: 2,
    from: "Mumbai",
    to: "Pune",
    distance: "150 km",
    duration: "3 hrs",
    image: "/popular_cab_route9.jpg",
    popular: true,
  },
  {
    id: 3,
    from: "Bengaluru",
    to: "Mysuru",
    distance: "145 km",
    duration: "3 hrs",
    image: "/popular_cab_route8.jpg",
    popular: true,
  },
  {
    id: 4,
    from: "Chennai",
    to: "Puducherry",
    distance: "155 km",
    duration: "3 hrs",
    image: "/popular_cab_route1.jpg",
    popular: true,
  },
  {
    id: 5,
    from: "Jaipur",
    to: "Udaipur",
    distance: "395 km",
    duration: "6.5 hrs",
    image: "/popular_cab_route2.jpg",
    popular: false,
  },
  {
    id: 6,
    from: "Kolkata",
    to: "Digha",
    distance: "185 km",
    duration: "4 hrs",
    image: "/popular_cab_route3.jpg",
    popular: false,
  },
  {
    id: 7,
    from: "Hyderabad",
    to: "Srisailam",
    distance: "215 km",
    duration: "5 hrs",
    image: "/popular_cab_route5.jpg",
    popular: false,
  },
  {
    id: 8,
    from: "Ahmedabad",
    to: "Statue of Unity",
    distance: "200 km",
    duration: "4 hrs",
    image: "/popular_cab_route4.png",
    popular: true,
  },
  {
    id: 9,
    from: "Dehradun",
    to: "Mussoorie",
    distance: "35 km",
    duration: "1 hr",
    image: "/popular_cab_route6.jpg",
    popular: true,
  },
  {
    id: 10,
    from: "Kochi",
    to: "Munnar",
    distance: "130 km",
    duration: "4 hrs",
    image: "/package_kerala.jpg",
    popular: true,
  },
];