export const popularRoutes = [
  {
    id: 1,
    from: "Lucknow",
    to: "Ayodhya",
    distance: "135 km",
    duration: "2.5 hrs",
    image: "/lucknow.jpg",
    popular: true,
  },
  {
    id: 2,
    from: "Ayodhya",
    to: "Varanasi",
    distance: "210 km",
    duration: "4 hrs",
    image: "/services_darshan.jpg",
    popular: true,
  },
  {
    id: 3,
    from: "Varanasi",
    to: "Prayagraj",
    distance: "120 km",
    duration: "2.5 hrs",
    image: "/boat5.jpg",
    popular: true,
  },
  {
    id: 4,
    from: "Delhi",
    to: "Ayodhya",
    distance: "560 km",
    duration: "9 hrs",
    image: "/delhi.jpg",
    popular: true,
  },
  {
    id: 5,
    from: "Ayodhya",
    to: "Prayagraj",
    distance: "165 km",
    duration: "3.5 hrs",
    image: "/Hero-2.jpg",
    popular: false,
  },
  {
    id: 6,
    from: "Varanasi",
    to: "Gorakhpur",
    distance: "195 km",
    duration: "4 hrs",
    image: "/boat5.jpg",
    popular: false,
  },
  {
    id: 7,
    from: "Lucknow",
    to: "Varanasi",
    distance: "320 km",
    duration: "6 hrs",
    image: "/lucknow.jpg",
    popular: true,
  },
  {
    id: 8,
    from: "Ayodhya",
    to: "Naimisharanya",
    distance: "100 km",
    duration: "2.5 hrs",
    image: "/Hero-2.jpg",
    popular: false,
  },
  {
    id: 9,
    from: "Varanasi",
    to: "Sarnath",
    distance: "10 km",
    duration: "30 mins",
    image: "/Hero-4.jpg",
    popular: true,
  },
  {
    id: 10,
    from: "Ayodhya",
    to: "Mathura",
    distance: "380 km",
    duration: "7 hrs",
    image: "/Hero-2.jpg",
    popular: false,
  },
];
