export const taxiFleet = [
  {
    id: 1,
    category: "GROUP",
    name: "Tempo Traveller",
    image: "/20-seater-tempo.jpg",
    seating: "12 to 26 Seats",
    features: ["Push-back Seats", "Powerful AC", "Group Travel"],
    buttonText: "Book Tempo Traveller",
    slug: "tempo-traveller-taxi",
  },
  {
    id: 2,
    category: "LUXURY",
    name: "Urbania Rental",
    image: "/urbania/Urbania.png",
    seating: "17 Seats",
    features: ["Premium Comfort", "Recliner Seats", "Luxury Travel"],
    buttonText: "Book Urbania",
    slug: "urbania-rental-taxi",
  },
  {
    id: 3,
    category: "PREMIUM",
    name: "Innova Crysta Taxi",
    image: "/innova.avif",
    seating: "6+1 Seats",
    features: ["Premium Comfort", "Spacious Interior", "Outstation Ready"],
    buttonText: "Book Innova Crysta",
    slug: "innova-crysta-taxi",
  },
  {
    id: 4,
    category: "SUV",
    name: "Ertiga Taxi",
    image: "/ertiga_white.jpg",
    seating: "6+1 Seats",
    features: ["Family Travel", "Extra Luggage", "All India Permit"],
    buttonText: "Book Ertiga",
    slug: "ertiga-taxi",
  },
  {
    id: 5,
    category: "SEDAN",
    name: "Dzire Taxi",
    image: "/dezire_white.png",
    seating: "4+1 Seats",
    features: ["Comfortable", "Budget Friendly", "Experienced Driver"],
    buttonText: "Book Dzire",
    slug: "dzire-taxi",
  },
  {
    id: 6,
    category: "SEDAN",
    name: "Etios Taxi",
    image: "/etios.avif",
    seating: "4+1 Seats",
    features: ["Reliable", "Spacious Boot", "Smooth Highway Ride"],
    buttonText: "Book Etios",
    slug: "etios-taxi",
  },
  {
    id: 7,
    category: "SEDAN",
    name: "Amaze Taxi",
    image: "/amaze.webp",
    seating: "4+1 Seats",
    features: ["Smooth Ride", "Budget Friendly", "AC Comfort"],
    buttonText: "Book Amaze",
    slug: "amaze-taxi",
  },
];