export const vehicleFleet = [
  {
    id: 1,
    category: "HATCHBACK",
    name: "Swift",
    image: "/swift.avif",
    seating: "4+1 Seats",
    features: ["Fuel Efficient", "Budget Friendly"],
    buttonText: "Book Swift",
    slug: "swift-cab",
  },
  {
    id: 2,
    category: "SEDAN",
    name: "Dzire",
    image: "/dezire_white.png",
    seating: "4+1 Seats",
    features: ["Comfortable", "Budget Friendly"],
    buttonText: "Book Sedan",
    slug: "sedan-cab",
  },

  {
    id: 3,
    category: "SUV",
    name: "Ertiga",
    image: "/ertiga_white.jpg",
    seating: "6+1 Seats",
    features: ["Extra Luggage", "Family Travel"],
    buttonText: "Book SUV",
    slug: "ertiga-cab",
  },
  {
    id: 4,
    category: "SUV",
    name: "Creta",
    image: "/Creta.avif",
    seating: "6+1 Seats",
    features: ["Powerful SUV", "Spacious Interior"],
    buttonText: "Book Creta",
    slug: "Creta-cab",
  },

  {
    id: 5,
    category: "PREMIUM",
    name: "Innova Crysta",
    image: "/Innova.avif",
    seating: "6+1 Seats",
    features: ["Premium Comfort", "Spacious"],
    buttonText: "Book Innova",
    slug: "innova-crysta-cab",
  },
];
