export const vehicleFleet = [
  {
    id: 1,
    category: "SEDAN",
    name: "Swift Dzire",
    image: "/dezire_white.png",
    seating: "4+1 Seats",
    price: "from ₹11/km",
    offer: "10% Off",
    features: ["Comfortable", "Budget Friendly"],
    buttonText: "Book Dzire",
    slug: "dzire-cab",
  },

  {
    id: 2,
    category: "SEDAN",
    name: "Amaze",
    image: "/amaze.webp",
    seating: "4+1 Seats",
    price: "from ₹12/km",
    offer: "10% Off",
    features: ["Comfortable", "Spacious Boot"],
    buttonText: "Book Amaze",
    slug: "amaze-cab",
  },

  {
    id: 3,
    category: "SUV",
    name: "Maruti Ertiga",
    image: "/ertiga_white.jpg",
    seating: "6+1 Seats",
    price: "from ₹14/km",
    offer: "10% Off",
    features: ["Extra Luggage", "Family Travel"],
    buttonText: "Book Ertiga",
    slug: "ertiga-cab",
  },

  {
    id: 4,
    category: "SEDAN",
    name: "Etios",
    image: "/etios.avif",
    seating: "4+1 Seats",
    price: "from ₹12/km",
    offer: "10% Off",
    features: ["Comfortable", "Reliable"],
    buttonText: "Book Etios",
    slug: "etios-cab",
  },

  {
    id: 5,
    category: "PREMIUM",
    name: "Innova Crysta",
    image: "/innova.avif",
    seating: "6+1 Seats",
    price: "from ₹18/km",
    offer: "10% Off",
    features: ["Premium Comfort", "Spacious"],
    buttonText: "Book Innova Crysta",
    slug: "innova-crysta-cab",
  },

  {
    id: 6,
    category: "SUV",
    name: "Creta",
    image: "/Creta.avif",
    seating: "5 Seats",
    price: "from ₹14/km",
    offer: "10% Off",
    features: ["Powerful SUV", "Spacious Interior"],
    buttonText: "Book Creta",
    slug: "creta-cab",
  },
];