
const routes = [
    // 1. Lucknow & Immediate Neighbors
    { slug: "barabanki", fromCity: "Barabanki", toCity: "Lucknow", distance: 40, duration: "0.5 - 1.5 hrs" },
    { slug: "unnao", fromCity: "Unnao", toCity: "Lucknow", distance: 20, duration: "0.5 - 1.5 hrs" },
    { slug: "sitapur", fromCity: "Sitapur", toCity: "Lucknow", distance: 90, duration: "0.5 - 1.5 hrs" },
    { slug: "hardoi", fromCity: "Hardoi", toCity: "Lucknow", distance: 110, duration: "0.5 - 1.5 hrs" },
    { slug: "raebareli", fromCity: "Raebareli", toCity: "Lucknow", distance: 80, duration: "0.5 - 1.5 hrs" },
    { slug: "sandila", fromCity: "Sandila", toCity: "Lucknow", distance: 59, duration: "0.5 - 1.5 hrs" },
    { slug: "mallawan", fromCity: "Mallawan", toCity: "Lucknow", distance: 44, duration: "0.5 - 1.5 hrs" },
    { slug: "bilgram", fromCity: "Bilgram", toCity: "Lucknow", distance: 21, duration: "0.5 - 1.5 hrs" },
    { slug: "mahmudabad", fromCity: "Mahmudabad", toCity: "Lucknow", distance: 47, duration: "0.5 - 1.5 hrs" },
    { slug: "biswan", fromCity: "Biswan", toCity: "Lucknow", distance: 48, duration: "0.5 - 1.5 hrs" },
    { slug: "laharpur", fromCity: "Laharpur", toCity: "Lucknow", distance: 25, duration: "0.5 - 1.5 hrs" },
    { slug: "haidergarh", fromCity: "Haidergarh", toCity: "Lucknow", distance: 25, duration: "0.5 - 1.5 hrs" },
    { slug: "rudauli", fromCity: "Rudauli", toCity: "Lucknow", distance: 35, duration: "0.5 - 1.5 hrs" },
    { slug: "milkipur", fromCity: "Milkipur", toCity: "Lucknow", distance: 33, duration: "0.5 - 1.5 hrs" },
    { slug: "satrikh", fromCity: "Satrikh", toCity: "Lucknow", distance: 47, duration: "0.5 - 1.5 hrs" },
    { slug: "nigohan", fromCity: "Nigohan", toCity: "Lucknow", distance: 39, duration: "0.5 - 1.5 hrs" },
    { slug: "itaunja", fromCity: "Itaunja", toCity: "Lucknow", distance: 41, duration: "0.5 - 1.5 hrs" },
    { slug: "bakshi-ka-talab", fromCity: "Bakshi Ka Talab", toCity: "Lucknow", distance: 41, duration: "0.5 - 1.5 hrs" },
    { slug: "kakori", fromCity: "Kakori", toCity: "Lucknow", distance: 49, duration: "0.5 - 1.5 hrs" },
    { slug: "malihabad", fromCity: "Malihabad", toCity: "Lucknow", distance: 27, duration: "0.5 - 1.5 hrs" },
    { slug: "mohanlalganj", fromCity: "Mohanlalganj", toCity: "Lucknow", distance: 30, duration: "0.5 - 1.5 hrs" },
    { slug: "safedabad", fromCity: "Safedabad", toCity: "Lucknow", distance: 28, duration: "0.5 - 1.5 hrs" },
    { slug: "sidhauli", fromCity: "Sidhauli", toCity: "Lucknow", distance: 45, duration: "0.5 - 1.5 hrs" },
    { slug: "misrikh", fromCity: "Misrikh", toCity: "Lucknow", distance: 23, duration: "0.5 - 1.5 hrs" },
    { slug: "hargaon", fromCity: "Hargaon", toCity: "Lucknow", distance: 51, duration: "0.5 - 1.5 hrs" },
    { slug: "nindaura", fromCity: "Nindaura", toCity: "Lucknow", distance: 43, duration: "0.5 - 1.5 hrs" },

    // 2. Eastern UP (Ayodhya, Amethi, Sultanpur, Jaunpur, Varanasi Belt)
    { slug: "ayodhya", fromCity: "Ayodhya", toCity: "Lucknow", distance: 130, duration: "2.5 - 6 hrs" },
    { slug: "amethi", fromCity: "Amethi", toCity: "Lucknow", distance: 130, duration: "2.5 - 6 hrs" },
    { slug: "sultanpur", fromCity: "Sultanpur", toCity: "Lucknow", distance: 110, duration: "2.5 - 6 hrs" },
    { slug: "gauriganj", fromCity: "Gauriganj", toCity: "Lucknow", distance: 145, duration: "2.5 - 6 hrs" },
    { slug: "jais", fromCity: "Jais", toCity: "Lucknow", distance: 135, duration: "2.5 - 6 hrs" },
    { slug: "musafirkhana", fromCity: "Musafirkhana", toCity: "Lucknow", distance: 160, duration: "2.5 - 6 hrs" },
    { slug: "jagdishpur", fromCity: "Jagdishpur", toCity: "Lucknow", distance: 137, duration: "2.5 - 6 hrs" },
    { slug: "tiloi", fromCity: "Tiloi", toCity: "Lucknow", distance: 149, duration: "2.5 - 6 hrs" },
    { slug: "kadipur", fromCity: "Kadipur", toCity: "Lucknow", distance: 205, duration: "2.5 - 6 hrs" },
    { slug: "lambhua", fromCity: "Lambhua", toCity: "Lucknow", distance: 223, duration: "2.5 - 6 hrs" },
    { slug: "jaunpur", fromCity: "Jaunpur", toCity: "Lucknow", distance: 210, duration: "2.5 - 6 hrs" },
    { slug: "machhlishahr", fromCity: "Machhlishahr", toCity: "Lucknow", distance: 265, duration: "2.5 - 6 hrs" },
    { slug: "mariahu", fromCity: "Mariahu", toCity: "Lucknow", distance: 186, duration: "2.5 - 6 hrs" },
    { slug: "kerakat", fromCity: "Kerakat", toCity: "Lucknow", distance: 203, duration: "2.5 - 6 hrs" },
    { slug: "shahganj", fromCity: "Shahganj", toCity: "Lucknow", distance: 131, duration: "2.5 - 6 hrs" },
    { slug: "goshainganj", fromCity: "Goshainganj", toCity: "Lucknow", distance: 176, duration: "2.5 - 6 hrs" },
    { slug: "varanasi", fromCity: "Varanasi", toCity: "Lucknow", distance: 280, duration: "2.5 - 6 hrs" },
    { slug: "gyanpur", fromCity: "Gyanpur", toCity: "Lucknow", distance: 225, duration: "2.5 - 6 hrs" },
    { slug: "bhadohi-sant-ravidas-nagar", fromCity: "Bhadohi (Sant Ravidas Nagar)", toCity: "Lucknow", distance: 254, duration: "2.5 - 6 hrs" },
    { slug: "suriyawan", fromCity: "Suriyawan", toCity: "Lucknow", distance: 141, duration: "2.5 - 6 hrs" },
    { slug: "aurai", fromCity: "Aurai", toCity: "Lucknow", distance: 256, duration: "2.5 - 6 hrs" },
    { slug: "gopiganj", fromCity: "Gopiganj", toCity: "Lucknow", distance: 104, duration: "2.5 - 6 hrs" },
    { slug: "khamaria", fromCity: "Khamaria", toCity: "Lucknow", distance: 222, duration: "2.5 - 6 hrs" },
    { slug: "chandauli", fromCity: "Chandauli", toCity: "Lucknow", distance: 217, duration: "2.5 - 6 hrs" },
    { slug: "sakaldiha", fromCity: "Sakaldiha", toCity: "Lucknow", distance: 115, duration: "2.5 - 6 hrs" },
    { slug: "chakia", fromCity: "Chakia", toCity: "Lucknow", distance: 174, duration: "2.5 - 6 hrs" },
    { slug: "mirzapur", fromCity: "Mirzapur", toCity: "Lucknow", distance: 258, duration: "2.5 - 6 hrs" },
    { slug: "lalganj", fromCity: "Lalganj", toCity: "Lucknow", distance: 173, duration: "2.5 - 6 hrs" },
    { slug: "ahraura", fromCity: "Ahraura", toCity: "Lucknow", distance: 196, duration: "2.5 - 6 hrs" },
    { slug: "chunar", fromCity: "Chunar", toCity: "Lucknow", distance: 214, duration: "2.5 - 6 hrs" },
    { slug: "marihan", fromCity: "Marihan", toCity: "Lucknow", distance: 149, duration: "2.5 - 6 hrs" },
    { slug: "sonbhadra", fromCity: "Sonbhadra", toCity: "Lucknow", distance: 149, duration: "2.5 - 6 hrs" },
    { slug: "robertsganj", fromCity: "Robertsganj", toCity: "Lucknow", distance: 119, duration: "2.5 - 6 hrs" },
    { slug: "obra", fromCity: "Obra", toCity: "Lucknow", distance: 104, duration: "2.5 - 6 hrs" },
    { slug: "renukoot", fromCity: "Renukoot", toCity: "Lucknow", distance: 111, duration: "2.5 - 6 hrs" },
    { slug: "dudhi", fromCity: "Dudhi", toCity: "Lucknow", distance: 158, duration: "2.5 - 6 hrs" },
    { slug: "ghorawal", fromCity: "Ghorawal", toCity: "Lucknow", distance: 262, duration: "2.5 - 6 hrs" },

    // 3. North-Eastern UP (Gorakhpur, Basti, Deoria, Ballia, Azamgarh Belt)
    { slug: "gorakhpur", fromCity: "Gorakhpur", toCity: "Lucknow", distance: 280, duration: "3 - 6.5 hrs" },
    { slug: "campierganj", fromCity: "Campierganj", toCity: "Lucknow", distance: 225, duration: "3 - 6.5 hrs" },
    { slug: "sahjanwa", fromCity: "Sahjanwa", toCity: "Lucknow", distance: 222, duration: "3 - 6.5 hrs" },
    { slug: "bansgaon", fromCity: "Bansgaon", toCity: "Lucknow", distance: 284, duration: "3 - 6.5 hrs" },
    { slug: "gola", fromCity: "Gola", toCity: "Lucknow", distance: 204, duration: "3 - 6.5 hrs" },
    { slug: "khajni", fromCity: "Khajni", toCity: "Lucknow", distance: 294, duration: "3 - 6.5 hrs" },
    { slug: "basti", fromCity: "Basti", toCity: "Lucknow", distance: 200, duration: "3 - 6.5 hrs" },
    { slug: "rudhauli", fromCity: "Rudhauli", toCity: "Lucknow", distance: 172, duration: "3 - 6.5 hrs" },
    { slug: "bansi", fromCity: "Bansi", toCity: "Lucknow", distance: 164, duration: "3 - 6.5 hrs" },
    { slug: "domariyaganj", fromCity: "Domariyaganj", toCity: "Lucknow", distance: 253, duration: "3 - 6.5 hrs" },
    { slug: "shohratgarh", fromCity: "Shohratgarh", toCity: "Lucknow", distance: 220, duration: "3 - 6.5 hrs" },
    { slug: "naugarh", fromCity: "Naugarh", toCity: "Lucknow", distance: 272, duration: "3 - 6.5 hrs" },
    { slug: "khalilabad", fromCity: "Khalilabad", toCity: "Lucknow", distance: 186, duration: "3 - 6.5 hrs" },
    { slug: "sant-kabir-nagar", fromCity: "Sant Kabir Nagar", toCity: "Lucknow", distance: 236, duration: "3 - 6.5 hrs" },
    { slug: "siddharthnagar", fromCity: "Siddharthnagar", toCity: "Lucknow", distance: 220, duration: "3 - 6.5 hrs" },
    { slug: "itwa", fromCity: "Itwa", toCity: "Lucknow", distance: 288, duration: "3 - 6.5 hrs" },
    { slug: "maharajganj", fromCity: "Maharajganj", toCity: "Lucknow", distance: 171, duration: "3 - 6.5 hrs" },
    { slug: "pharenda", fromCity: "Pharenda", toCity: "Lucknow", distance: 271, duration: "3 - 6.5 hrs" },
    { slug: "nautanwa", fromCity: "Nautanwa", toCity: "Lucknow", distance: 196, duration: "3 - 6.5 hrs" },
    { slug: "kushinagar", fromCity: "Kushinagar", toCity: "Lucknow", distance: 274, duration: "3 - 6.5 hrs" },
    { slug: "kasia", fromCity: "Kasia", toCity: "Lucknow", distance: 235, duration: "3 - 6.5 hrs" },
    { slug: "tamkuhi-raj", fromCity: "Tamkuhi Raj", toCity: "Lucknow", distance: 157, duration: "3 - 6.5 hrs" },
    { slug: "hata", fromCity: "Hata", toCity: "Lucknow", distance: 300, duration: "3 - 6.5 hrs" },
    { slug: "fazilnagar", fromCity: "Fazilnagar", toCity: "Lucknow", distance: 220, duration: "3 - 6.5 hrs" },
    { slug: "deoria", fromCity: "Deoria", toCity: "Lucknow", distance: 300, duration: "3 - 6.5 hrs" },
    { slug: "rudrapur", fromCity: "Rudrapur", toCity: "Lucknow", distance: 190, duration: "3 - 6.5 hrs" },
    { slug: "salempur", fromCity: "Salempur", toCity: "Lucknow", distance: 285, duration: "3 - 6.5 hrs" },
    { slug: "bhatpar-rani", fromCity: "Bhatpar Rani", toCity: "Lucknow", distance: 176, duration: "3 - 6.5 hrs" },
    { slug: "ballia", fromCity: "Ballia", toCity: "Lucknow", distance: 280, duration: "3 - 6.5 hrs" },
    { slug: "rasra", fromCity: "Rasra", toCity: "Lucknow", distance: 253, duration: "3 - 6.5 hrs" },
    { slug: "belthara-road", fromCity: "Belthara Road", toCity: "Lucknow", distance: 271, duration: "3 - 6.5 hrs" },
    { slug: "bansdih", fromCity: "Bansdih", toCity: "Lucknow", distance: 265, duration: "3 - 6.5 hrs" },
    { slug: "sikanderpur", fromCity: "Sikanderpur", toCity: "Lucknow", distance: 218, duration: "3 - 6.5 hrs" },
    { slug: "dildarnagar", fromCity: "Dildarnagar", toCity: "Lucknow", distance: 168, duration: "3 - 6.5 hrs" },
    { slug: "mau", fromCity: "Mau", toCity: "Lucknow", distance: 294, duration: "3 - 6.5 hrs" },
    { slug: "ghosi", fromCity: "Ghosi", toCity: "Lucknow", distance: 264, duration: "3 - 6.5 hrs" },
    { slug: "muhammadpur", fromCity: "Muhammadpur", toCity: "Lucknow", distance: 153, duration: "3 - 6.5 hrs" },
    { slug: "azamgarh", fromCity: "Azamgarh", toCity: "Lucknow", distance: 220, duration: "3 - 6.5 hrs" },
    { slug: "sagri", fromCity: "Sagri", toCity: "Lucknow", distance: 290, duration: "3 - 6.5 hrs" },
    { slug: "martingan", fromCity: "Martingan", toCity: "Lucknow", distance: 260, duration: "3 - 6.5 hrs" },
    { slug: "mehnaun", fromCity: "Mehnaun", toCity: "Lucknow", distance: 151, duration: "3 - 6.5 hrs" },
    { slug: "ambedkar-nagar", fromCity: "Ambedkar Nagar", toCity: "Lucknow", distance: 281, duration: "3 - 6.5 hrs" },
    { slug: "jalalpur", fromCity: "Jalalpur", toCity: "Lucknow", distance: 205, duration: "3 - 6.5 hrs" },
    { slug: "tanda", fromCity: "Tanda", toCity: "Lucknow", distance: 265, duration: "3 - 6.5 hrs" },
    { slug: "akbarpur", fromCity: "Akbarpur", toCity: "Lucknow", distance: 222, duration: "3 - 6.5 hrs" },

    // 4. Northern UP (Bahraich, Balrampur, Gonda, Lakhimpur, Hardoi Belt)
    { slug: "bahraich", fromCity: "Bahraich", toCity: "Lucknow", distance: 130, duration: "1.5 - 4 hrs" },
    { slug: "nanpara", fromCity: "Nanpara", toCity: "Lucknow", distance: 151, duration: "1.5 - 4 hrs" },
    { slug: "mihinpurwa", fromCity: "Mihinpurwa", toCity: "Lucknow", distance: 63, duration: "1.5 - 4 hrs" },
    { slug: "kaisarganj", fromCity: "Kaisarganj", toCity: "Lucknow", distance: 151, duration: "1.5 - 4 hrs" },
    { slug: "payagpur", fromCity: "Payagpur", toCity: "Lucknow", distance: 103, duration: "1.5 - 4 hrs" },
    { slug: "ramnagar", fromCity: "Ramnagar", toCity: "Lucknow", distance: 151, duration: "1.5 - 4 hrs" },
    { slug: "balrampur", fromCity: "Balrampur", toCity: "Lucknow", distance: 169, duration: "1.5 - 4 hrs" },
    { slug: "tulsipur", fromCity: "Tulsipur", toCity: "Lucknow", distance: 147, duration: "1.5 - 4 hrs" },
    { slug: "utraula", fromCity: "Utraula", toCity: "Lucknow", distance: 100, duration: "1.5 - 4 hrs" },
    { slug: "shravasti", fromCity: "Shravasti", toCity: "Lucknow", distance: 135, duration: "1.5 - 4 hrs" },
    { slug: "gonda", fromCity: "Gonda", toCity: "Lucknow", distance: 67, duration: "1.5 - 4 hrs" },
    { slug: "mankapur", fromCity: "Mankapur", toCity: "Lucknow", distance: 85, duration: "1.5 - 4 hrs" },
    { slug: "colonelganj", fromCity: "Colonelganj", toCity: "Lucknow", distance: 128, duration: "1.5 - 4 hrs" },
    { slug: "tarabganj", fromCity: "Tarabganj", toCity: "Lucknow", distance: 151, duration: "1.5 - 4 hrs" },
    { slug: "lakhimpur-kheri", fromCity: "Lakhimpur Kheri", toCity: "Lucknow", distance: 97, duration: "1.5 - 4 hrs" },
    { slug: "nighasan", fromCity: "Nighasan", toCity: "Lucknow", distance: 176, duration: "1.5 - 4 hrs" },
    { slug: "dhaurahra", fromCity: "Dhaurahra", toCity: "Lucknow", distance: 87, duration: "1.5 - 4 hrs" },
    { slug: "mohammadi", fromCity: "Mohammadi", toCity: "Lucknow", distance: 155, duration: "1.5 - 4 hrs" },
    { slug: "mitauli", fromCity: "Mitauli", toCity: "Lucknow", distance: 153, duration: "1.5 - 4 hrs" },
    { slug: "gola-gokarannath", fromCity: "Gola Gokarannath", toCity: "Lucknow", distance: 105, duration: "1.5 - 4 hrs" },
    { slug: "palia", fromCity: "Palia", toCity: "Lucknow", distance: 132, duration: "1.5 - 4 hrs" },
    { slug: "khairabad", fromCity: "Khairabad", toCity: "Lucknow", distance: 69, duration: "1.5 - 4 hrs" },
    { slug: "shahabad", fromCity: "Shahabad", toCity: "Lucknow", distance: 164, duration: "1.5 - 4 hrs" },
    { slug: "sandi", fromCity: "Sandi", toCity: "Lucknow", distance: 104, duration: "1.5 - 4 hrs" },
    { slug: "sawayajpur", fromCity: "Sawayajpur", toCity: "Lucknow", distance: 170, duration: "1.5 - 4 hrs" },
    { slug: "pihani", fromCity: "Pihani", toCity: "Lucknow", distance: 62, duration: "1.5 - 4 hrs" },
    { slug: "gopamau", fromCity: "Gopamau", toCity: "Lucknow", distance: 124, duration: "1.5 - 4 hrs" },

    // 5. Western & Central UP (Kanpur, Agra, Aligarh, Bareilly, Meerut Divisions)
    { slug: "kanpur-nagar", fromCity: "Kanpur Nagar", toCity: "Lucknow", distance: 80, duration: "2 - 8 hrs" },
    { slug: "kanpur-dehat", fromCity: "Kanpur Dehat", toCity: "Lucknow", distance: 134, duration: "2 - 8 hrs" },
    { slug: "ghatampur", fromCity: "Ghatampur", toCity: "Lucknow", distance: 353, duration: "2 - 8 hrs" },
    { slug: "bithoor", fromCity: "Bithoor", toCity: "Lucknow", distance: 136, duration: "2 - 8 hrs" },
    { slug: "nawabganj", fromCity: "Nawabganj", toCity: "Lucknow", distance: 271, duration: "2 - 8 hrs" },
    { slug: "bangarmau", fromCity: "Bangarmau", toCity: "Lucknow", distance: 282, duration: "2 - 8 hrs" },
    { slug: "derapur", fromCity: "Derapur", toCity: "Lucknow", distance: 341, duration: "2 - 8 hrs" },
    { slug: "pukhrayan", fromCity: "Pukhrayan", toCity: "Lucknow", distance: 431, duration: "2 - 8 hrs" },
    { slug: "auraiya", fromCity: "Auraiya", toCity: "Lucknow", distance: 212, duration: "2 - 8 hrs" },
    { slug: "etawah", fromCity: "Etawah", toCity: "Lucknow", distance: 180, duration: "2 - 8 hrs" },
    { slug: "jaswantnagar", fromCity: "Jaswantnagar", toCity: "Lucknow", distance: 438, duration: "2 - 8 hrs" },
    { slug: "bharthana", fromCity: "Bharthana", toCity: "Lucknow", distance: 173, duration: "2 - 8 hrs" },
    { slug: "mainpuri", fromCity: "Mainpuri", toCity: "Lucknow", distance: 246, duration: "2 - 8 hrs" },
    { slug: "farrukhabad", fromCity: "Farrukhabad", toCity: "Lucknow", distance: 160, duration: "2 - 8 hrs" },
    { slug: "kannauj", fromCity: "Kannauj", toCity: "Lucknow", distance: 432, duration: "2 - 8 hrs" },
    { slug: "chhibramau", fromCity: "Chhibramau", toCity: "Lucknow", distance: 206, duration: "2 - 8 hrs" },
    { slug: "tirwa", fromCity: "Tirwa", toCity: "Lucknow", distance: 417, duration: "2 - 8 hrs" },
    { slug: "saurikh", fromCity: "Saurikh", toCity: "Lucknow", distance: 179, duration: "2 - 8 hrs" },
    { slug: "agra", fromCity: "Agra", toCity: "Lucknow", distance: 330, duration: "2 - 8 hrs" },
    { slug: "tundla", fromCity: "Tundla", toCity: "Lucknow", distance: 394, duration: "2 - 8 hrs" },
    { slug: "shikohabad", fromCity: "Shikohabad", toCity: "Lucknow", distance: 118, duration: "2 - 8 hrs" },
    { slug: "etmadpur", fromCity: "Etmadpur", toCity: "Lucknow", distance: 148, duration: "2 - 8 hrs" },
    { slug: "mathura", fromCity: "Mathura", toCity: "Lucknow", distance: 280, duration: "2 - 8 hrs" },
    { slug: "chhata", fromCity: "Chhata", toCity: "Lucknow", distance: 118, duration: "2 - 8 hrs" },
    { slug: "govardhan", fromCity: "Govardhan", toCity: "Lucknow", distance: 192, duration: "2 - 8 hrs" },
    { slug: "mahavan", fromCity: "Mahavan", toCity: "Lucknow", distance: 268, duration: "2 - 8 hrs" },
    { slug: "sadabad", fromCity: "Sadabad", toCity: "Lucknow", distance: 366, duration: "2 - 8 hrs" },
    { slug: "jalesar", fromCity: "Jalesar", toCity: "Lucknow", distance: 294, duration: "2 - 8 hrs" },
    { slug: "fatehabad", fromCity: "Fatehabad", toCity: "Lucknow", distance: 317, duration: "2 - 8 hrs" },
    { slug: "aligarh", fromCity: "Aligarh", toCity: "Lucknow", distance: 250, duration: "2 - 8 hrs" },
    { slug: "khair", fromCity: "Khair", toCity: "Lucknow", distance: 366, duration: "2 - 8 hrs" },
    { slug: "gabhana", fromCity: "Gabhana", toCity: "Lucknow", distance: 137, duration: "2 - 8 hrs" },
    { slug: "iglas", fromCity: "Iglas", toCity: "Lucknow", distance: 85, duration: "2 - 8 hrs" },
    { slug: "sikandra-rao", fromCity: "Sikandra Rao", toCity: "Lucknow", distance: 277, duration: "2 - 8 hrs" },
    { slug: "hathras", fromCity: "Hathras", toCity: "Lucknow", distance: 230, duration: "2 - 8 hrs" },
    { slug: "hasayan", fromCity: "Hasayan", toCity: "Lucknow", distance: 395, duration: "2 - 8 hrs" },
    { slug: "bilram", fromCity: "Bilram", toCity: "Lucknow", distance: 120, duration: "2 - 8 hrs" },
    { slug: "etah", fromCity: "Etah", toCity: "Lucknow", distance: 261, duration: "2 - 8 hrs" },
    { slug: "aliganj", fromCity: "Aliganj", toCity: "Lucknow", distance: 146, duration: "2 - 8 hrs" },
    { slug: "patiyali", fromCity: "Patiyali", toCity: "Lucknow", distance: 273, duration: "2 - 8 hrs" },
    { slug: "kasganj", fromCity: "Kasganj", toCity: "Lucknow", distance: 181, duration: "2 - 8 hrs" },
    { slug: "bareilly", fromCity: "Bareilly", toCity: "Lucknow", distance: 220, duration: "2 - 8 hrs" },
    { slug: "faridpur", fromCity: "Faridpur", toCity: "Lucknow", distance: 239, duration: "2 - 8 hrs" },
    { slug: "budaun", fromCity: "Budaun", toCity: "Lucknow", distance: 240, duration: "2 - 8 hrs" },
    { slug: "gunnaur", fromCity: "Gunnaur", toCity: "Lucknow", distance: 336, duration: "2 - 8 hrs" },
    { slug: "bisauli", fromCity: "Bisauli", toCity: "Lucknow", distance: 449, duration: "2 - 8 hrs" },
    { slug: "bilsi", fromCity: "Bilsi", toCity: "Lucknow", distance: 187, duration: "2 - 8 hrs" },
    { slug: "pilibhit", fromCity: "Pilibhit", toCity: "Lucknow", distance: 250, duration: "2 - 8 hrs" },
    { slug: "puranpur", fromCity: "Puranpur", toCity: "Lucknow", distance: 106, duration: "2 - 8 hrs" },
    { slug: "shahjahanpur", fromCity: "Shahjahanpur", toCity: "Lucknow", distance: 180, duration: "2 - 8 hrs" },
    { slug: "jalalabad", fromCity: "Jalalabad", toCity: "Lucknow", distance: 92, duration: "2 - 8 hrs" },
    { slug: "tilhar", fromCity: "Tilhar", toCity: "Lucknow", distance: 81, duration: "2 - 8 hrs" },
    { slug: "powayan", fromCity: "Powayan", toCity: "Lucknow", distance: 337, duration: "2 - 8 hrs" },
    { slug: "moradabad", fromCity: "Moradabad", toCity: "Lucknow", distance: 350, duration: "2 - 8 hrs" },
    { slug: "chandausi", fromCity: "Chandausi", toCity: "Lucknow", distance: 147, duration: "2 - 8 hrs" },
    { slug: "sambhal", fromCity: "Sambhal", toCity: "Lucknow", distance: 336, duration: "2 - 8 hrs" },
    { slug: "amroha", fromCity: "Amroha", toCity: "Lucknow", distance: 348, duration: "2 - 8 hrs" },
    { slug: "dhanaura", fromCity: "Dhanaura", toCity: "Lucknow", distance: 160, duration: "2 - 8 hrs" },
    { slug: "rampur", fromCity: "Rampur", toCity: "Lucknow", distance: 147, duration: "2 - 8 hrs" },
    { slug: "bilaspur", fromCity: "Bilaspur", toCity: "Lucknow", distance: 180, duration: "2 - 8 hrs" },
    { slug: "suar", fromCity: "Suar", toCity: "Lucknow", distance: 404, duration: "2 - 8 hrs" },
    { slug: "bijnor", fromCity: "Bijnor", toCity: "Lucknow", distance: 208, duration: "2 - 8 hrs" },
    { slug: "najibabad", fromCity: "Najibabad", toCity: "Lucknow", distance: 151, duration: "2 - 8 hrs" },
    { slug: "dhampur", fromCity: "Dhampur", toCity: "Lucknow", distance: 339, duration: "2 - 8 hrs" },
    { slug: "meerut", fromCity: "Meerut", toCity: "Lucknow", distance: 450, duration: "2 - 8 hrs" },
    { slug: "sardhana", fromCity: "Sardhana", toCity: "Lucknow", distance: 362, duration: "2 - 8 hrs" },
    { slug: "ghaziabad", fromCity: "Ghaziabad", toCity: "Lucknow", distance: 480, duration: "2 - 8 hrs" },
    { slug: "loni", fromCity: "Loni", toCity: "Lucknow", distance: 239, duration: "2 - 8 hrs" },
    { slug: "hapur", fromCity: "Hapur", toCity: "Lucknow", distance: 184, duration: "2 - 8 hrs" },
    { slug: "dhaulana", fromCity: "Dhaulana", toCity: "Lucknow", distance: 159, duration: "2 - 8 hrs" },
    { slug: "bulandshahr", fromCity: "Bulandshahr", toCity: "Lucknow", distance: 380, duration: "2 - 8 hrs" },
    { slug: "sikandrabad", fromCity: "Sikandrabad", toCity: "Lucknow", distance: 92, duration: "2 - 8 hrs" },
    { slug: "khurja", fromCity: "Khurja", toCity: "Lucknow", distance: 345, duration: "2 - 8 hrs" },
    { slug: "shamli", fromCity: "Shamli", toCity: "Lucknow", distance: 391, duration: "2 - 8 hrs" },
    { slug: "kairana", fromCity: "Kairana", toCity: "Lucknow", distance: 310, duration: "2 - 8 hrs" },
    { slug: "muzaffarnagar", fromCity: "Muzaffarnagar", toCity: "Lucknow", distance: 420, duration: "2 - 8 hrs" },
    { slug: "budhana", fromCity: "Budhana", toCity: "Lucknow", distance: 103, duration: "2 - 8 hrs" },
    { slug: "baghpat", fromCity: "Baghpat", toCity: "Lucknow", distance: 263, duration: "2 - 8 hrs" },
    { slug: "khekada", fromCity: "Khekada", toCity: "Lucknow", distance: 88, duration: "2 - 8 hrs" },
    { slug: "saharanpur", fromCity: "Saharanpur", toCity: "Lucknow", distance: 500, duration: "2 - 8 hrs" },
    { slug: "roorkee", fromCity: "Roorkee", toCity: "Lucknow", distance: 186, duration: "2 - 8 hrs" },
    { slug: "rampur-maniharan", fromCity: "Rampur Maniharan", toCity: "Lucknow", distance: 438, duration: "2 - 8 hrs" },

    // 6. Bundelkhand Region (Jhansi, Banda, Chitrakoot, Fatehpur, Prayagraj)
    { slug: "jhansi", fromCity: "Jhansi", toCity: "Lucknow", distance: 250, duration: "2.5 - 5.5 hrs" },
    { slug: "garautha", fromCity: "Garautha", toCity: "Lucknow", distance: 181, duration: "2.5 - 5.5 hrs" },
    { slug: "mauranipur", fromCity: "Mauranipur", toCity: "Lucknow", distance: 193, duration: "2.5 - 5.5 hrs" },
    { slug: "lalitpur", fromCity: "Lalitpur", toCity: "Lucknow", distance: 280, duration: "2.5 - 5.5 hrs" },
    { slug: "talbehat", fromCity: "Talbehat", toCity: "Lucknow", distance: 262, duration: "2.5 - 5.5 hrs" },
    { slug: "mahoba", fromCity: "Mahoba", toCity: "Lucknow", distance: 210, duration: "2.5 - 5.5 hrs" },
    { slug: "charkhari", fromCity: "Charkhari", toCity: "Lucknow", distance: 147, duration: "2.5 - 5.5 hrs" },
    { slug: "kulpahar", fromCity: "Kulpahar", toCity: "Lucknow", distance: 125, duration: "2.5 - 5.5 hrs" },
    { slug: "hamirpur", fromCity: "Hamirpur", toCity: "Lucknow", distance: 180, duration: "2.5 - 5.5 hrs" },
    { slug: "rath", fromCity: "Rath", toCity: "Lucknow", distance: 240, duration: "2.5 - 5.5 hrs" },
    { slug: "maudaha", fromCity: "Maudaha", toCity: "Lucknow", distance: 206, duration: "2.5 - 5.5 hrs" },
    { slug: "banda", fromCity: "Banda", toCity: "Lucknow", distance: 220, duration: "2.5 - 5.5 hrs" },
    { slug: "naraini", fromCity: "Naraini", toCity: "Lucknow", distance: 171, duration: "2.5 - 5.5 hrs" },
    { slug: "baberu", fromCity: "Baberu", toCity: "Lucknow", distance: 218, duration: "2.5 - 5.5 hrs" },
    { slug: "chitrakoot", fromCity: "Chitrakoot", toCity: "Lucknow", distance: 230, duration: "2.5 - 5.5 hrs" },
    { slug: "karwi", fromCity: "Karwi", toCity: "Lucknow", distance: 149, duration: "2.5 - 5.5 hrs" },
    { slug: "manikpur", fromCity: "Manikpur", toCity: "Lucknow", distance: 228, duration: "2.5 - 5.5 hrs" },
    { slug: "rajapur", fromCity: "Rajapur", toCity: "Lucknow", distance: 204, duration: "2.5 - 5.5 hrs" },
    { slug: "bindki", fromCity: "Bindki", toCity: "Lucknow", distance: 202, duration: "2.5 - 5.5 hrs" },
    { slug: "khaga", fromCity: "Khaga", toCity: "Lucknow", distance: 129, duration: "2.5 - 5.5 hrs" },
    { slug: "kishunpur", fromCity: "Kishunpur", toCity: "Lucknow", distance: 236, duration: "2.5 - 5.5 hrs" },
    { slug: "asothar", fromCity: "Asothar", toCity: "Lucknow", distance: 198, duration: "2.5 - 5.5 hrs" },
    { slug: "prayagraj", fromCity: "Prayagraj", toCity: "Lucknow", distance: 200, duration: "2.5 - 5.5 hrs" },
    { slug: "phulpur", fromCity: "Phulpur", toCity: "Lucknow", distance: 270, duration: "2.5 - 5.5 hrs" },
    { slug: "meja", fromCity: "Meja", toCity: "Lucknow", distance: 258, duration: "2.5 - 5.5 hrs" },
    { slug: "handia", fromCity: "Handia", toCity: "Lucknow", distance: 119, duration: "2.5 - 5.5 hrs" },
    { slug: "koraon", fromCity: "Koraon", toCity: "Lucknow", distance: 202, duration: "2.5 - 5.5 hrs" },
    { slug: "bara", fromCity: "Bara", toCity: "Lucknow", distance: 276, duration: "2.5 - 5.5 hrs" },
    { slug: "karachhana", fromCity: "Karachhana", toCity: "Lucknow", distance: 129, duration: "2.5 - 5.5 hrs" },
    { slug: "chail", fromCity: "Chail", toCity: "Lucknow", distance: 160, duration: "2.5 - 5.5 hrs" },
    { slug: "sirathu", fromCity: "Sirathu", toCity: "Lucknow", distance: 159, duration: "2.5 - 5.5 hrs" },
    { slug: "manjhanpur", fromCity: "Manjhanpur", toCity: "Lucknow", distance: 185, duration: "2.5 - 5.5 hrs" },
    { slug: "kaushambi", fromCity: "Kaushambi", toCity: "Lucknow", distance: 250, duration: "2.5 - 5.5 hrs" },
    { slug: "patti", fromCity: "Patti", toCity: "Lucknow", distance: 145, duration: "2.5 - 5.5 hrs" },
    { slug: "raniganj", fromCity: "Raniganj", toCity: "Lucknow", distance: 138, duration: "2.5 - 5.5 hrs" },
    { slug: "unchahar", fromCity: "Unchahar", toCity: "Lucknow", distance: 188, duration: "2.5 - 5.5 hrs" },
    { slug: "salon", fromCity: "Salon", toCity: "Lucknow", distance: 147, duration: "2.5 - 5.5 hrs" },
    { slug: "sareni", fromCity: "Sareni", toCity: "Lucknow", distance: 106, duration: "2.5 - 5.5 hrs" },
    { slug: "dalmau", fromCity: "Dalmau", toCity: "Lucknow", distance: 120, duration: "2.5 - 5.5 hrs" },
    { slug: "parshadepur", fromCity: "Parshadepur", toCity: "Lucknow", distance: 147, duration: "2.5 - 5.5 hrs" },
];

export default function LucknowRoutesSection() {
    return (
        <section className="py-12 px-4 bg-gray-50">
            <div className="max-w-7xl mx-auto">
                <h2 className="text-3xl font-bold text-center text-gray-900 mb-2">
                    Book Cab to Lucknow from 250+ Cities
                </h2>
                <p className="text-center text-gray-500 mb-8">
                    Choose your pickup city and book a cab to Lucknow
                </p>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                    {routes.map((route) => (
                        <a
                            key={route.slug}
                            href={`/route/${route.slug}-to-lucknow-taxi`}
                            className="block bg-white rounded-lg border border-gray-200 p-4 hover:shadow-md hover:border-orange-400 transition-all"
                        >
                            <div className="flex items-center justify-between mb-2">
                                <span className="font-semibold text-gray-900">
                                    {route.fromCity}
                                </span>
                                <span className="text-orange-500 text-xl">→</span>
                                <span className="font-semibold text-orange-600">
                                    {route.toCity}
                                </span>
                            </div>
                            <div className="flex items-center justify-between text-sm text-gray-500">
                                <span>📍 {route.distance} km</span>
                                <span>🕐 {route.duration}</span>
                            </div>
                        </a>
                    ))}
                </div>
            </div>
        </section>
    );
}